//! BBL file envelope: HEADER / CONFIG / EXECUTABLE blocks, machine start/end, timelapse.

use std::fmt::Write as _;

use bambu_config::{config_block_gcode, expand_placeholders, PlaceholderContext};
use bambu_geom::{unscale, Point};
use bambu_slicer::SliceResult;

use crate::cooling::set_exhaust_fan_gcode;
use crate::motion::Writer;
use crate::parse::parse_axis;
use crate::GcodeError;

impl Writer<'_> {
    pub(crate) fn emit_header(&mut self, max_z: f64) -> Result<(), GcodeError> {
        writeln!(self.out, "; HEADER_BLOCK_START")?;
        writeln!(self.out, "; generated by bambu-cli (safe-Rust rewrite)")?;
        writeln!(self.out, ";_GP_ESTIMATED_PRINTING_TIME_PLACEHOLDER")?;
        writeln!(self.out, ";_GP_TOTAL_LAYER_NUMBER_PLACEHOLDER")?;
        writeln!(self.out, ";_GP_FILAMENT_USED_LENGTH_PLACEHOLDER")?;
        writeln!(self.out, ";_GP_FILAMENT_USED_VOLUME_PLACEHOLDER")?;
        writeln!(self.out, ";_GP_FILAMENT_USED_WEIGHT_PLACEHOLDER")?;
        writeln!(
            self.out,
            "; filament_density: {}",
            header_num(self.settings.filament_density_g_cm3)
        )?;
        writeln!(
            self.out,
            "; filament_diameter: {}",
            header_num(self.settings.filament_diameter_mm)
        )?;
        writeln!(self.out, "; max_z_height: {max_z:.2}")?;
        writeln!(self.out, "; filament: 1")?;
        writeln!(self.out, "; support_material_on_wipe_tower: 0")?;
        writeln!(self.out, "; HEADER_BLOCK_END")?;
        writeln!(self.out)?;
        match config_block_gcode(self.settings) {
            Ok(block) => self.out.push_str(&block),
            Err(_) => {
                writeln!(self.out, "; CONFIG_BLOCK_START")?;
                writeln!(self.out, "; CONFIG_BLOCK_END")?;
            }
        }
        writeln!(self.out)?;
        writeln!(self.out, "; EXECUTABLE_BLOCK_START")?;
        writeln!(self.out, ";_GP_FIRST_LINE_M73_PLACEHOLDER")?;
        Ok(())
    }

    pub(crate) fn emit_start(
        &mut self,
        ctx: Option<&PlaceholderContext>,
    ) -> Result<(), GcodeError> {
        if self.settings.machine_start_gcode.is_empty() {
            writeln!(self.out, "M104 S{}", self.settings.temperature_c)?;
            writeln!(self.out, "M140 S{}", self.settings.bed_temperature_c)?;
            writeln!(self.out, "G90")?;
            writeln!(self.out, "G21")?;
            writeln!(self.out, "G28")?;
            writeln!(self.out, "M109 S{}", self.settings.temperature_c)?;
            writeln!(self.out, "M190 S{}", self.settings.bed_temperature_c)?;
            writeln!(self.out, "G92 E0")?;
        } else {
            let ctx = ctx.expect("start gcode context");
            writeln!(self.out, "; FEATURE: Custom")?;
            emit_expanded(&mut self.out, &self.settings.machine_start_gcode, ctx);
            writeln!(self.out, "; MACHINE_START_GCODE_END")?;
            emit_expanded(&mut self.out, &self.settings.filament_start_gcode, ctx);
            writeln!(self.out, ";VT0 H0")?;
            writeln!(self.out, "G90")?;
            writeln!(self.out, "G21")?;
            writeln!(self.out, "M82 ; use absolute distances for extrusion")?;
            writeln!(self.out, "G92 E0")?;
            writeln!(self.out, "M981 S1 P20000 ;open spaghetti detector")?;
        }
        if self.settings.support_air_filtration && self.settings.activate_air_filtration {
            self.out.push_str(&set_exhaust_fan_gcode(
                self.settings.during_print_exhaust_fan_speed,
            ));
        }
        Ok(())
    }

    pub(crate) fn emit_layer_change_gcode(
        &mut self,
        layer_i: usize,
        print_z: f64,
        total_layers: usize,
        max_z: f64,
    ) -> Result<(), GcodeError> {
        if self.settings.layer_change_gcode.is_empty() {
            return Ok(());
        }
        let mut ctx = PlaceholderContext::new();
        ctx.set("layer_num", layer_i);
        ctx.set("total_layer_count", total_layers);
        ctx.set("layer_z", print_z);
        ctx.set("max_layer_z", max_z);
        let custom = expand_placeholders(&self.settings.layer_change_gcode, &ctx);
        self.out.push_str(custom.trim_end());
        self.out.push('\n');
        Ok(())
    }

    pub(crate) fn emit_time_lapse(
        &mut self,
        layer_i: usize,
        print_z: f64,
        max_z: f64,
    ) -> Result<(), GcodeError> {
        if self.settings.time_lapse_gcode.is_empty() {
            return Ok(());
        }
        let ctx = self
            .settings
            .placeholder_timelapse_context(layer_i, print_z, max_z);
        let start = self.out.len();
        emit_expanded(&mut self.out, &self.settings.time_lapse_gcode, &ctx);
        if let Some(z) = last_g1_z(&self.out[start..]) {
            if (z - print_z).abs() > 1e-3 {
                writeln!(self.out, "G1 Z{print_z:.3}")?;
            }
        }
        Ok(())
    }

    /// C++ `insert_wrapping_detection_gcode`: once per layer, before the first extruder.
    pub(crate) fn emit_wrapping_detection(
        &mut self,
        layer_i: usize,
        print_z: f64,
        max_z: f64,
    ) -> Result<(), GcodeError> {
        if !self.settings.enable_wrapping_detection {
            return Ok(());
        }
        self.retract()?;
        if self.settings.wrapping_detection_gcode.is_empty() {
            return Ok(());
        }
        let ctx = self
            .settings
            .placeholder_wrapping_context(layer_i, print_z, max_z);
        let start = self.out.len();
        emit_expanded(&mut self.out, &self.settings.wrapping_detection_gcode, &ctx);
        if let Some(z) = last_g1_z(&self.out[start..]) {
            self.state.z = z;
            self.state.lifted = 0.0;
        }
        Ok(())
    }

    pub(crate) fn emit_end(&mut self, ctx: Option<&PlaceholderContext>) -> Result<(), GcodeError> {
        if !self.settings.machine_start_gcode.is_empty() {
            writeln!(self.out, "M981 S0 P20000 ; close spaghetti detector")?;
        }
        if self.settings.machine_end_gcode.is_empty() {
            writeln!(self.out, "M104 S0")?;
            writeln!(self.out, "M140 S0")?;
            writeln!(self.out, "G28 X0 Y0")?;
            writeln!(self.out, "M84")?;
        } else {
            let ctx = ctx.expect("end gcode context");
            writeln!(self.out, "; FEATURE: Custom")?;
            writeln!(self.out, "; MACHINE_END_GCODE_START")?;
            emit_expanded(&mut self.out, &self.settings.filament_end_gcode, ctx);
            emit_expanded(&mut self.out, &self.settings.machine_end_gcode, ctx);
        }
        writeln!(self.out, ";_GP_LAST_LINE_M73_PLACEHOLDER")?;
        writeln!(self.out, "; EXECUTABLE_BLOCK_END")?;
        writeln!(self.out)?;
        if self.settings.support_air_filtration && self.settings.activate_air_filtration {
            self.out.push_str(&set_exhaust_fan_gcode(
                self.settings.complete_print_exhaust_fan_speed,
            ));
        }
        Ok(())
    }
}

fn emit_expanded(out: &mut String, template: &str, ctx: &PlaceholderContext) {
    if template.is_empty() {
        return;
    }
    let custom = expand_placeholders(template, ctx);
    let trimmed = custom.trim_end();
    if !trimmed.is_empty() {
        out.push_str(trimmed);
        out.push('\n');
    }
}

fn last_g1_z(gcode: &str) -> Option<f64> {
    let mut z = None;
    for line in gcode.lines() {
        let trimmed = match line.find(';') {
            Some(i) => line[..i].trim(),
            None => line.trim(),
        };
        let upper = trimmed.to_ascii_uppercase();
        if upper.starts_with("G0") || upper.starts_with("G1") {
            if let Some(v) = parse_axis(&upper, b'Z') {
                z = Some(v);
            }
        }
    }
    z
}

fn header_num(v: f64) -> String {
    if v.is_finite() && (v - v.round()).abs() < 1e-9 {
        format!("{}", v.round() as i64)
    } else {
        format!("{v}")
    }
}

pub(crate) fn first_layer_print_box(sliced: &SliceResult) -> ((f64, f64), (f64, f64)) {
    let Some(layer) = sliced.layers.first() else {
        return ((0.0, 0.0), (0.0, 0.0));
    };
    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    let mut visit = |pts: &[Point]| {
        for p in pts {
            let x = unscale(p.x);
            let y = unscale(p.y);
            min_x = min_x.min(x);
            min_y = min_y.min(y);
            max_x = max_x.max(x);
            max_y = max_y.max(y);
        }
    };
    for poly in &layer.contours {
        visit(poly);
    }
    for path in layer
        .brim
        .iter()
        .chain(layer.skirt.iter())
        .chain(layer.support.iter())
    {
        visit(path);
    }
    if !min_x.is_finite() {
        return ((0.0, 0.0), (0.0, 0.0));
    }
    ((min_x, min_y), (max_x - min_x, max_y - min_y))
}
