#![forbid(unsafe_code)]

mod cooling;
mod processor;

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use bambu_config::{
    expand_placeholders, Flow, PlaceholderContext, PrintAccel, SliceSettings, ZHopType,
};
use bambu_geom::{intersect_polygons, offset_polygons, unscale, Point, Polygon, Polyline};
use bambu_slicer::{classify_overhang, SliceResult};
use thiserror::Error;

pub use cooling::{
    additional_fan_percent, apply_layer_cooling_slowdown, apply_part_cooling, part_fan_percent,
    set_additional_fan_gcode, set_exhaust_fan_gcode, set_fan_gcode,
};
pub use processor::{format_time_dhms, process_gcode, ProcessorResult};

#[derive(Debug, Error)]
pub enum GcodeError {
    #[error("format: {0}")]
    Format(#[from] std::fmt::Error),
}

pub fn write_gcode(settings: &SliceSettings, sliced: &SliceResult) -> Result<String, GcodeError> {
    let mut out = String::new();
    writeln!(out, "; generated by bambu-cli (safe-Rust rewrite)")?;
    writeln!(out, ";LAYER_COUNT:{}", sliced.layers.len())?;
    if let Some(last) = sliced.layers.last() {
        writeln!(out, "; max_z_height: {:.2}", last.print_z_mm)?;
    }
    let custom_ctx =
        if settings.machine_start_gcode.is_empty() && settings.machine_end_gcode.is_empty() {
            None
        } else {
            let max_layer_z = sliced.layers.last().map(|l| l.print_z_mm).unwrap_or(0.0);
            let (first_min, first_size) = first_layer_print_box(sliced);
            Some(settings.placeholder_custom_gcode_context(
                sliced.layers.len().saturating_sub(1),
                sliced.layers.len(),
                max_layer_z,
                first_min,
                first_size,
            ))
        };
    if settings.machine_start_gcode.is_empty() {
        writeln!(out, "M104 S{}", settings.temperature_c)?;
        writeln!(out, "M140 S{}", settings.bed_temperature_c)?;
        writeln!(out, "G90")?;
        writeln!(out, "G21")?;
        writeln!(out, "G28")?;
        writeln!(out, "M109 S{}", settings.temperature_c)?;
        writeln!(out, "M190 S{}", settings.bed_temperature_c)?;
        writeln!(out, "G92 E0")?;
    } else {
        let ctx = custom_ctx.as_ref().expect("start gcode context");
        writeln!(out, "; FEATURE: Custom")?;
        emit_expanded(&mut out, &settings.machine_start_gcode, ctx);
        writeln!(out, "; MACHINE_START_GCODE_END")?;
        emit_expanded(&mut out, &settings.filament_start_gcode, ctx);
        writeln!(out, ";VT0 H0")?;
        writeln!(out, "G90")?;
        writeln!(out, "G21")?;
        writeln!(out, "M82 ; use absolute distances for extrusion")?;
        writeln!(out, "G92 E0")?;
    }
    if settings.support_air_filtration && settings.activate_air_filtration {
        out.push_str(&set_exhaust_fan_gcode(
            settings.during_print_exhaust_fan_speed,
        ));
    }

    let travel_f = settings.travel_speed_mm_s * 60.0;
    let outer_f = settings.print_speed_mm_s * 60.0;
    let inner_f = settings.inner_wall_speed_mm_s * 60.0;
    let first_f = settings.first_layer_speed_mm_s * 60.0;
    let first_infill_f = settings.first_layer_infill_speed_mm_s * 60.0;
    let infill_f = settings.infill_speed_mm_s * 60.0;
    let gap_f = settings.gap_infill_speed_mm_s * 60.0;
    let solid_f = settings.solid_infill_speed_mm_s * 60.0;
    let support_f = settings.support_speed_mm_s * 60.0;
    let support_interface_f = settings.support_interface_speed_mm_s * 60.0;

    let mut state = WriterState {
        print_accel: settings.print_acceleration_mm_s2(true, PrintAccel::Default),
        ..WriterState::default()
    };
    for (layer_i, layer) in sliced.layers.iter().enumerate() {
        let first = layer_i == 0;
        state.lift_overhangs = lift_overhangs_in_window(&sliced.layers, layer.print_z_mm);
        if layer_i > 0 && settings.retract_when_changing_layer {
            retract(&mut out, settings, &mut state)?;
        }
        writeln!(out, "; CHANGE_LAYER")?;
        writeln!(out, ";LAYER:{}", layer.index)?;
        writeln!(out, "; LAYER_HEIGHT:{}", layer.height_mm)?;
        state.first_layer = first;
        emit_accel(
            &mut out,
            &mut state,
            settings.travel_acceleration_for_layer(first),
        )?;
        writeln!(out, "G1 Z{:.3} F600", layer.print_z_mm)?;
        state.z = layer.print_z_mm;
        state.lifted = 0.0;
        if !settings.layer_change_gcode.is_empty() {
            let mut ctx = PlaceholderContext::new();
            ctx.set("layer_num", layer_i);
            ctx.set("total_layer_count", sliced.layers.len());
            ctx.set("layer_z", layer.print_z_mm);
            if let Some(last) = sliced.layers.last() {
                ctx.set("max_layer_z", last.print_z_mm);
            }
            let custom = expand_placeholders(&settings.layer_change_gcode, &ctx);
            out.push_str(custom.trim_end());
            out.push('\n');
        }
        if layer_i == 1 && !settings.layer_change_gcode.is_empty() {
            writeln!(out, "; open powerlost recovery")?;
            writeln!(out, "M1003 S1")?;
        }
        writeln!(out, ";_SET_FAN_SPEED_CHANGING_LAYER")?;
        let flow = Flow::from_settings(settings, layer.height_mm);
        let e_per_mm = flow.e_per_mm();
        let mm3_per_mm = flow.mm3_per_mm();
        let wall_f = if first { first_f } else { outer_f };
        let inner_wall_f = if first { first_f } else { inner_f };
        let sparse_f = if first { first_infill_f } else { infill_f };
        let gap_layer_f = if first { first_f } else { gap_f };
        let solid_layer_f = if first { first_f } else { solid_f };
        let support_layer_f = if first { first_f } else { support_f };
        let support_interface_layer_f = if first { first_f } else { support_interface_f };
        let bridge_layer_f = if first {
            first_f
        } else {
            settings.bridge_speed_mm_s * 60.0
        };
        let top_layer_f = if first {
            first_f
        } else {
            settings.top_surface_speed_mm_s * 60.0
        };
        let support_polys = if layer_i == 0 {
            None
        } else {
            overhang_rings(settings, sliced.layers.get(layer_i - 1))
        };

        if !layer.skirt.is_empty() {
            writeln!(out, "; FEATURE: Skirt")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.skirt,
                true,
                e_per_mm,
                wall_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.brim.is_empty() {
            writeln!(out, "; FEATURE: Brim")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.brim,
                true,
                e_per_mm,
                wall_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.support.is_empty() {
            writeln!(out, "; FEATURE: Support")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.support,
                false,
                e_per_mm,
                support_layer_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.support_interface.is_empty() {
            writeln!(out, "; FEATURE: Support interface")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.support_interface,
                false,
                e_per_mm,
                support_interface_layer_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        set_print_role(&mut state, settings, PrintAccel::OuterWall);
        emit_wall_paths(
            &mut out,
            "Outer wall",
            &layer.outer_walls,
            true,
            e_per_mm,
            wall_f,
            settings,
            travel_f,
            support_polys.as_deref(),
            settings.enable_overhang_speed,
            !first,
            mm3_per_mm,
            &mut state,
        )?;
        set_print_role(&mut state, settings, PrintAccel::InnerWall);
        emit_wall_paths(
            &mut out,
            "Inner wall",
            &layer.inner_walls,
            true,
            e_per_mm,
            inner_wall_f,
            settings,
            travel_f,
            support_polys.as_deref(),
            settings.enable_overhang_speed,
            !first,
            mm3_per_mm,
            &mut state,
        )?;
        if !layer.gap_infill.is_empty() {
            writeln!(out, "; FEATURE: Gap infill")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.gap_infill,
                false,
                e_per_mm,
                gap_layer_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.infill.is_empty() {
            writeln!(out, "; FEATURE: Sparse infill")?;
            set_print_role(&mut state, settings, PrintAccel::SparseInfill);
            emit_paths(
                &mut out,
                &layer.infill,
                false,
                e_per_mm,
                sparse_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.solid_infill.is_empty() {
            writeln!(out, "; FEATURE: Internal solid infill")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.solid_infill,
                false,
                e_per_mm,
                solid_layer_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.bridge.is_empty() {
            writeln!(out, "; FEATURE: Bridge")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_marked(
                &mut out,
                settings.overhang_fan_applies(5, true, false),
                ";_OVERHANG_FAN_START",
                ";_OVERHANG_FAN_END",
                |o| {
                    emit_paths(
                        o,
                        &layer.bridge,
                        false,
                        e_per_mm,
                        bridge_layer_f,
                        travel_f,
                        settings,
                        mm3_per_mm,
                        &mut state,
                    )
                },
            )?;
        }
        if !layer.bottom_surface.is_empty() {
            writeln!(out, "; FEATURE: Bottom surface")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            emit_paths(
                &mut out,
                &layer.bottom_surface,
                false,
                e_per_mm,
                wall_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.top_surface.is_empty() {
            writeln!(out, "; FEATURE: Top surface")?;
            set_print_role(&mut state, settings, PrintAccel::TopSurface);
            emit_paths(
                &mut out,
                &layer.top_surface,
                false,
                e_per_mm,
                top_layer_f,
                travel_f,
                settings,
                mm3_per_mm,
                &mut state,
            )?;
        }
        if !layer.ironing.is_empty() {
            writeln!(out, "; FEATURE: Ironing")?;
            set_print_role(&mut state, settings, PrintAccel::Default);
            let iron_flow =
                Flow::from_settings(settings, layer.height_mm * settings.ironing_flow.max(0.0));
            let iron_e = iron_flow.e_per_mm();
            let iron_f = settings.ironing_speed_mm_s * 60.0;
            let iron_closed = layer.ironing.iter().any(|p| p.len() > 2);
            emit_marked(
                &mut out,
                settings.ironing_fan_speed >= 0,
                ";_IRONING_FAN_START",
                ";_IRONING_FAN_END",
                |o| {
                    emit_paths(
                        o,
                        &layer.ironing,
                        iron_closed,
                        iron_e,
                        iron_f,
                        travel_f,
                        settings,
                        iron_flow.mm3_per_mm(),
                        &mut state,
                    )
                },
            )?;
        }
    }

    if settings.machine_end_gcode.is_empty() {
        writeln!(out, "M104 S0")?;
        writeln!(out, "M140 S0")?;
        writeln!(out, "G28 X0 Y0")?;
        writeln!(out, "M84")?;
    } else {
        let ctx = custom_ctx.as_ref().expect("end gcode context");
        writeln!(out, "; FEATURE: Custom")?;
        writeln!(out, "; MACHINE_END_GCODE_START")?;
        emit_expanded(&mut out, &settings.filament_end_gcode, ctx);
        emit_expanded(&mut out, &settings.machine_end_gcode, ctx);
    }
    if settings.support_air_filtration && settings.activate_air_filtration {
        out.push_str(&set_exhaust_fan_gcode(
            settings.complete_print_exhaust_fan_speed,
        ));
    }
    out = apply_layer_cooling_slowdown(&out, settings);
    out = apply_part_cooling(&out, settings);
    let stats = process_gcode(&out, settings);
    out.push_str(&stats.footer_lines());
    Ok(out)
}

fn emit_expanded(out: &mut String, template: &str, ctx: &PlaceholderContext) {
    if template.is_empty() {
        return;
    }
    let custom = expand_placeholders(template, ctx);
    let trimmed = custom.trim_end();
    if !trimmed.is_empty() {
        out.push_str(trimmed);
        out.push('\n');
    }
}

fn first_layer_print_box(sliced: &SliceResult) -> ((f64, f64), (f64, f64)) {
    let Some(layer) = sliced.layers.first() else {
        return ((0.0, 0.0), (0.0, 0.0));
    };
    let mut min_x = f64::INFINITY;
    let mut min_y = f64::INFINITY;
    let mut max_x = f64::NEG_INFINITY;
    let mut max_y = f64::NEG_INFINITY;
    let mut visit = |pts: &[Point]| {
        for p in pts {
            let x = unscale(p.x);
            let y = unscale(p.y);
            min_x = min_x.min(x);
            min_y = min_y.min(y);
            max_x = max_x.max(x);
            max_y = max_y.max(y);
        }
    };
    for poly in &layer.contours {
        visit(poly);
    }
    for path in layer
        .brim
        .iter()
        .chain(layer.skirt.iter())
        .chain(layer.support.iter())
    {
        visit(path);
    }
    if !min_x.is_finite() {
        return ((0.0, 0.0), (0.0, 0.0));
    }
    ((min_x, min_y), (max_x - min_x, max_y - min_y))
}

fn emit_marked(
    out: &mut String,
    mark: bool,
    start: &str,
    end: &str,
    body: impl FnOnce(&mut String) -> Result<(), GcodeError>,
) -> Result<(), GcodeError> {
    if mark {
        writeln!(out, "{start}")?;
    }
    body(out)?;
    if mark {
        writeln!(out, "{end}")?;
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn emit_paths(
    out: &mut String,
    paths: &[Polyline],
    closed: bool,
    e_per_mm: f64,
    print_f: f64,
    travel_f: f64,
    settings: &SliceSettings,
    mm3_per_mm: f64,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    let print_f = settings.cap_extrude_feed_mm_min(print_f, mm3_per_mm);
    for path in paths {
        emit_one_path(
            out, path, closed, e_per_mm, print_f, travel_f, settings, state, false,
        )?;
    }
    Ok(())
}

fn overhang_rings(
    settings: &SliceSettings,
    lower: Option<&bambu_slicer::Layer>,
) -> Option<Vec<Vec<Polygon>>> {
    if !settings.detect_overhang_wall {
        return None;
    }
    let lower = lower?;
    if lower.contours.is_empty() {
        return None;
    }
    let start = -0.5 * settings.line_width_mm;
    let end = 0.5 * settings.nozzle_diameter_mm;
    let mut rings = Vec::with_capacity(5);
    for i in 0..5 {
        let t = f64::from(i) / 4.0;
        let offset = start + t * (end - start);
        let grown = offset_polygons(&lower.contours, offset);
        rings.push(if grown.is_empty() {
            lower.contours.clone()
        } else {
            grown
        });
    }
    Some(rings)
}

fn overhang_feed(settings: &SliceSettings, degree: u8, print_f: f64) -> f64 {
    if !settings.enable_overhang_speed || degree == 0 {
        return print_f;
    }
    let band = match degree {
        1 => settings.overhang_1_4_speed_mm_s,
        2 => settings.overhang_2_4_speed_mm_s,
        3 => settings.overhang_3_4_speed_mm_s,
        4 => settings.overhang_4_4_speed_mm_s,
        _ => settings.overhang_speed_mm_s,
    };
    if band <= 0.0 {
        print_f
    } else {
        band * 60.0
    }
}

/// C++ `SMALL_PERIMETER_LENGTH`: circumference of a circle with the given radius.
fn small_perimeter_max_length_mm(threshold_mm: f64) -> f64 {
    std::f64::consts::TAU * threshold_mm
}

fn polyline_length_mm(path: &[Point], closed: bool) -> f64 {
    if path.len() < 2 {
        return 0.0;
    }
    let mut len = 0.0;
    for window in path.windows(2) {
        len += window[0].distance_mm(window[1]);
    }
    if closed {
        len += path[path.len() - 1].distance_mm(path[0]);
    }
    len
}

/// C++ `extrude_loop`: if the whole loop is a small perimeter, take `min` with the role speed.
fn small_perimeter_feed(
    settings: &SliceSettings,
    path: &[Point],
    closed: bool,
    print_f: f64,
) -> f64 {
    let speed = settings.small_perimeter_speed_mm_s();
    if speed <= 0.0 {
        return print_f;
    }
    if polyline_length_mm(path, closed)
        > small_perimeter_max_length_mm(settings.small_perimeter_threshold_mm)
    {
        return print_f;
    }
    print_f.min(speed * 60.0)
}

#[allow(clippy::too_many_arguments)]
fn emit_wall_paths(
    out: &mut String,
    supported_feature: &str,
    paths: &[Polyline],
    closed: bool,
    e_per_mm: f64,
    print_f: f64,
    settings: &SliceSettings,
    travel_f: f64,
    support: Option<&[Vec<Polygon>]>,
    slow_overhang: bool,
    apply_small: bool,
    mm3_per_mm: f64,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    if paths.is_empty() {
        return Ok(());
    }
    let mut current_feature: Option<&str> = None;
    for path in paths {
        if path.len() < 2 {
            continue;
        }
        let runs = match support {
            Some(rings) if !rings.is_empty() => classify_overhang(path, rings, closed),
            _ => vec![bambu_slicer::ClassifiedPath {
                path: path.clone(),
                degree: 0,
            }],
        };
        let single = runs.len() == 1;
        for run in &runs {
            if run.path.len() < 2 {
                continue;
            }
            let total = !run.inside() && slow_overhang;
            let feature = if total {
                "Overhang wall"
            } else {
                supported_feature
            };
            if current_feature != Some(feature) {
                writeln!(out, "; FEATURE: {feature}")?;
                current_feature = Some(feature);
            }
            let mut feed = overhang_feed(settings, run.degree, print_f);
            if apply_small {
                feed = small_perimeter_feed(settings, path, closed, feed);
            }
            feed = settings.cap_extrude_feed_mm_min(feed, mm3_per_mm);
            let boost =
                settings.overhang_fan_applies(run.degree, false, supported_feature == "Outer wall");
            emit_marked(
                out,
                boost,
                ";_OVERHANG_FAN_START",
                ";_OVERHANG_FAN_END",
                |o| {
                    emit_one_path(
                        o,
                        &run.path,
                        closed && single,
                        e_per_mm,
                        feed,
                        travel_f,
                        settings,
                        state,
                        supported_feature == "Outer wall",
                    )
                },
            )?;
        }
    }
    Ok(())
}

#[derive(Debug, Default)]
struct WriterState {
    e: f64,
    retracted: f64,
    last: Option<(f64, f64)>,
    wipe: Vec<(f64, f64)>,
    last_print_f: f64,
    z: f64,
    lifted: f64,
    /// C++ `m_to_lift`: hop height queued by `lazy_lift` until the next XY travel.
    to_lift: f64,
    to_lift_type: ZHopType,
    /// C++ `loverhangs` in the 0.4 mm Z window around the current layer.
    lift_overhangs: Vec<Polygon>,
    last_accel: f64,
    print_accel: f64,
    first_layer: bool,
    /// Upcoming extrusion is an outer/overhang wall (C++ short-travel accel).
    short_travel_role: bool,
}

const TRAVEL_EPS_MM: f64 = 1e-4;

fn set_print_role(state: &mut WriterState, settings: &SliceSettings, kind: PrintAccel) {
    state.print_accel = settings.print_acceleration_mm_s2(state.first_layer, kind);
    state.short_travel_role = kind == PrintAccel::OuterWall;
}

fn emit_accel(out: &mut String, state: &mut WriterState, accel: f64) -> Result<(), GcodeError> {
    if accel <= 0.0 {
        return Ok(());
    }
    let rounded = accel.round();
    if (rounded - state.last_accel).abs() < 0.5 {
        return Ok(());
    }
    state.last_accel = rounded;
    writeln!(out, "M204 P{:.0} ; adjust acceleration", rounded)?;
    Ok(())
}

fn xy_dist(a: (f64, f64), b: (f64, f64)) -> f64 {
    ((b.0 - a.0).powi(2) + (b.1 - a.1).powi(2)).sqrt()
}

fn xy_len(path: &[(f64, f64)]) -> f64 {
    path.windows(2).map(|w| xy_dist(w[0], w[1])).sum()
}

fn clip_prefix(path: &[(f64, f64)], max_len: f64) -> Vec<(f64, f64)> {
    if path.len() < 2 || max_len <= TRAVEL_EPS_MM {
        return Vec::new();
    }
    let mut out = vec![path[0]];
    let mut remaining = max_len;
    for window in path.windows(2) {
        let d = xy_dist(window[0], window[1]);
        if d <= remaining {
            out.push(window[1]);
            remaining -= d;
            if remaining <= TRAVEL_EPS_MM {
                break;
            }
        } else {
            let t = remaining / d;
            out.push((
                window[0].0 + (window[1].0 - window[0].0) * t,
                window[0].1 + (window[1].1 - window[0].1) * t,
            ));
            break;
        }
    }
    out
}

fn wipe_feed_mm_min(settings: &SliceSettings, state: &WriterState) -> f64 {
    if settings.role_base_wipe_speed && state.last_print_f > 1e-9 {
        state.last_print_f
    } else {
        settings.travel_speed_mm_s * settings.wipe_speed_percent / 100.0 * 60.0
    }
}

fn emit_retract_e(
    out: &mut String,
    settings: &SliceSettings,
    state: &mut WriterState,
    amount: f64,
) -> Result<(), GcodeError> {
    if amount <= 1e-9 {
        return Ok(());
    }
    state.e -= amount;
    state.retracted += amount;
    writeln!(
        out,
        "G1 E{:.5} F{:.0} ; retract",
        state.e,
        settings.retraction_speed_mm_s * 60.0
    )?;
    Ok(())
}

fn wipe(
    out: &mut String,
    settings: &SliceSettings,
    state: &mut WriterState,
    remaining: f64,
) -> Result<(), GcodeError> {
    if remaining <= 1e-9 || state.wipe.len() < 2 {
        return Ok(());
    }
    let path_len = xy_len(&state.wipe);
    if path_len <= TRAVEL_EPS_MM {
        return Ok(());
    }
    let mut wipe_dist = settings.wipe_distance_mm;
    if path_len < wipe_dist {
        wipe_dist = path_len;
    }
    wipe_dist = wipe_dist.max(1e-9);
    let clipped = clip_prefix(&state.wipe, wipe_dist);
    if clipped.len() < 2 {
        return Ok(());
    }
    let actual = xy_len(&clipped).max(1e-9);
    writeln!(out, "; WIPE_START")?;
    let wipe_f = wipe_feed_mm_min(settings, state);
    for window in clipped.windows(2) {
        let seg = xy_dist(window[0], window[1]);
        let d_e = remaining * (seg / actual) * 0.95;
        state.e -= d_e;
        state.retracted += d_e;
        writeln!(
            out,
            "G1 X{:.3} Y{:.3} E{:.5} F{:.0} ;_WIPE",
            window[1].0, window[1].1, state.e, wipe_f
        )?;
        state.last = Some(window[1]);
    }
    writeln!(out, "; WIPE_END")?;
    Ok(())
}

fn retract(
    out: &mut String,
    settings: &SliceSettings,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    let length = settings.retraction_length_mm;
    if length <= 1e-9 {
        state.wipe.clear();
        return Ok(());
    }
    let remaining = (length - state.retracted).max(0.0);
    if remaining > 1e-9 {
        let can_wipe = settings.wipe && settings.wipe_distance_mm > 1e-9 && state.wipe.len() >= 2;
        if can_wipe {
            let before = remaining * settings.retract_before_wipe.clamp(0.0, 1.0);
            emit_retract_e(out, settings, state, before)?;
            let leftover = (length - state.retracted).max(0.0);
            wipe(out, settings, state, leftover)?;
            let still = (length - state.retracted).max(0.0);
            emit_retract_e(out, settings, state, still)?;
        } else {
            emit_retract_e(out, settings, state, remaining)?;
        }
    }
    state.wipe.clear();
    queue_lift(settings, state);
    Ok(())
}

/// C++ `GCodeWriter::slope_threshold` (3°).
const SLOPE_THRESHOLD_RAD: f64 = 3.0 * std::f64::consts::PI / 180.0;

fn spiral_radius(hop: f64) -> f64 {
    hop / (2.0 * std::f64::consts::PI * SLOPE_THRESHOLD_RAD.atan())
}

/// C++ `lazy_lift`: remember the hop until the next XY travel.
fn queue_lift(settings: &SliceSettings, state: &mut WriterState) {
    if state.lifted > 1e-9 || state.to_lift > 1e-9 || !settings.z_hop_in_range(state.z) {
        return;
    }
    state.to_lift = settings.z_hop_mm;
    state.to_lift_type = settings.z_hop_type;
}

/// C++ `travel_to_xyz` hop that was delayed by `lazy_lift`.
/// Auto: spiral if the clipped travel hits `loverhangs`, else slope.
fn apply_lazy_lift(
    out: &mut String,
    dest: (f64, f64),
    travel_f: f64,
    settings: &SliceSettings,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    if state.to_lift <= 1e-9 {
        return Ok(());
    }
    let hop = state.to_lift;
    let hop_z = state.z + hop;
    state.to_lift = 0.0;
    state.lifted = hop;
    let z_feed = settings.z_travel_speed_mm_s() * 60.0;
    let Some(from) = state.last else {
        writeln!(out, "G1 Z{:.3} F{:.0} ; normal lift Z", hop_z, z_feed)?;
        state.z = hop_z;
        return Ok(());
    };
    let dist = xy_dist(from, dest);
    if dist > TRAVEL_EPS_MM {
        let lift = match state.to_lift_type {
            ZHopType::Auto => {
                if travel_through_overhang(from, dest, hop, &state.lift_overhangs) {
                    ZHopType::Spiral
                } else {
                    ZHopType::Slope
                }
            }
            other => other,
        };
        match lift {
            ZHopType::Spiral => {
                if let Some((i, j)) = spiral_ij_on_bed(from, dest, spiral_radius(hop), settings) {
                    writeln!(out, "G17")?;
                    writeln!(
                        out,
                        "G2 Z{:.3} I{:.3} J{:.3} P1 F{:.0} ; spiral lift Z",
                        hop_z, i, j, z_feed
                    )?;
                } else {
                    writeln!(out, "G1 Z{:.3} F{:.0} ; normal lift Z", hop_z, z_feed)?;
                }
            }
            ZHopType::Slope => {
                if hop.atan2(dist) < SLOPE_THRESHOLD_RAD {
                    let run = hop / SLOPE_THRESHOLD_RAD.tan();
                    let ux = (dest.0 - from.0) / dist;
                    let uy = (dest.1 - from.1) / dist;
                    writeln!(
                        out,
                        "G1 X{:.3} Y{:.3} Z{:.3} F{:.0} ; slope lift Z",
                        from.0 + ux * run,
                        from.1 + uy * run,
                        hop_z,
                        travel_f
                    )?;
                }
            }
            ZHopType::Normal | ZHopType::Auto => {
                writeln!(out, "G1 Z{:.3} F{:.0} ; normal lift Z", hop_z, z_feed)?;
            }
        }
    } else {
        writeln!(out, "G1 Z{:.3} F{:.0} ; normal lift Z", hop_z, z_feed)?;
    }
    state.z = hop_z;
    Ok(())
}

fn spiral_ij(from: (f64, f64), to: (f64, f64), radius: f64) -> (f64, f64) {
    let dx = to.0 - from.0;
    let dy = to.1 - from.1;
    let len = (dx * dx + dy * dy).sqrt();
    if len <= TRAVEL_EPS_MM {
        return (radius, 0.0);
    }
    let nx = dx / len;
    let ny = dy / len;
    (-ny * radius, nx * radius)
}

/// C++ `travel_to_xyz`: try CCW perp, then CW; otherwise no in-bed spiral.
fn spiral_ij_on_bed(
    from: (f64, f64),
    to: (f64, f64),
    radius: f64,
    settings: &SliceSettings,
) -> Option<(f64, f64)> {
    let (i, j) = spiral_ij(from, to, radius);
    if settings.spiral_arc_within_bed(from.0 + i, from.1 + j, radius) {
        return Some((i, j));
    }
    if settings.spiral_arc_within_bed(from.0 - i, from.1 - j, radius) {
        return Some((-i, -j));
    }
    None
}

/// C++ `protect_z` window used by `is_through_overhang`.
const LIFT_PROTECT_Z_MM: f64 = 0.4;
/// Half-width of the travel stroke used to emulate C++ `intersection_pl`.
const TRAVEL_HIT_HALF_WIDTH_MM: f64 = 0.02;

fn lift_overhangs_in_window(layers: &[bambu_slicer::Layer], print_z: f64) -> Vec<Polygon> {
    let z0 = (print_z - LIFT_PROTECT_Z_MM).max(0.0);
    layers
        .iter()
        .filter(|l| l.print_z_mm + 1e-9 >= z0 && l.print_z_mm <= print_z + 1e-9)
        .flat_map(|l| l.lift_overhangs.iter().cloned())
        .collect()
}

/// C++ Auto hop: clipped travel intersecting `loverhangs` → spiral, else slope.
fn travel_through_overhang(
    from: (f64, f64),
    dest: (f64, f64),
    hop: f64,
    overhangs: &[Polygon],
) -> bool {
    if overhangs.is_empty() {
        return false;
    }
    let dist = xy_dist(from, dest);
    if dist <= TRAVEL_EPS_MM {
        return false;
    }
    let clip = (hop / SLOPE_THRESHOLD_RAD.tan()).min(dist);
    let ux = (dest.0 - from.0) / dist;
    let uy = (dest.1 - from.1) / dist;
    let end = (from.0 + ux * clip, from.1 + uy * clip);
    let px = -uy * TRAVEL_HIT_HALF_WIDTH_MM;
    let py = ux * TRAVEL_HIT_HALF_WIDTH_MM;
    let stroke = vec![
        Point::from_mm(from.0 + px, from.1 + py),
        Point::from_mm(end.0 + px, end.1 + py),
        Point::from_mm(end.0 - px, end.1 - py),
        Point::from_mm(from.0 - px, from.1 - py),
    ];
    !intersect_polygons(&[stroke], overhangs).is_empty()
}

fn unlift(
    out: &mut String,
    settings: &SliceSettings,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    if state.lifted <= 1e-9 {
        state.to_lift = 0.0;
        return Ok(());
    }
    state.z -= state.lifted;
    state.lifted = 0.0;
    state.to_lift = 0.0;
    writeln!(
        out,
        "G1 Z{:.3} F{:.0} ; restore layer Z",
        state.z,
        settings.z_travel_speed_mm_s() * 60.0
    )?;
    Ok(())
}

fn unretract(
    out: &mut String,
    settings: &SliceSettings,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    unlift(out, settings, state)?;
    if state.retracted <= 1e-9 {
        return Ok(());
    }
    let d_e = state.retracted + settings.retract_restart_extra_mm;
    state.e += d_e;
    state.retracted = 0.0;
    writeln!(
        out,
        "G1 E{:.5} F{:.0} ; unretract",
        state.e,
        settings.deretract_speed_mm_s() * 60.0
    )?;
    Ok(())
}

fn travel_to(
    out: &mut String,
    dest: (f64, f64),
    travel_f: f64,
    settings: &SliceSettings,
    state: &mut WriterState,
) -> Result<(), GcodeError> {
    if let Some(prev) = state.last {
        let dist = xy_dist(prev, dest);
        if dist < TRAVEL_EPS_MM {
            return Ok(());
        }
        if dist + 1e-9 >= settings.retraction_minimum_travel_mm {
            retract(out, settings, state)?;
        }
        emit_accel(
            out,
            state,
            settings.travel_acceleration_for_move(state.first_layer, state.short_travel_role, dist),
        )?;
        apply_lazy_lift(out, dest, travel_f, settings, state)?;
    }
    if state.lifted > 1e-9 {
        writeln!(
            out,
            "G0 X{:.3} Y{:.3} Z{:.3} F{:.0}",
            dest.0, dest.1, state.z, travel_f
        )?;
    } else {
        writeln!(out, "G0 X{:.3} Y{:.3} F{:.0}", dest.0, dest.1, travel_f)?;
    }
    state.last = Some(dest);
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn emit_one_path(
    out: &mut String,
    path: &[Point],
    closed: bool,
    e_per_mm: f64,
    print_f: f64,
    travel_f: f64,
    settings: &SliceSettings,
    state: &mut WriterState,
    external_perimeter: bool,
) -> Result<(), GcodeError> {
    if path.len() < 2 {
        return Ok(());
    }
    let pts: Vec<(f64, f64)> = path.iter().copied().map(xy).collect();
    let start = pts[0];
    travel_to(out, start, travel_f, settings, state)?;
    unretract(out, settings, state)?;
    let print_accel = state.print_accel;
    emit_accel(out, state, print_accel)?;
    let n = pts.len();
    let end = if closed { n } else { n - 1 };
    let mut trail = vec![start];
    let marker = if external_perimeter {
        ";_EXTRUDE_SET_SPEED;_EXTERNAL_PERIMETER"
    } else {
        ""
    };
    for i in 0..end {
        let a = pts[i];
        let b = pts[(i + 1) % n];
        let dist = xy_dist(a, b);
        state.e += dist * e_per_mm;
        writeln!(
            out,
            "G1 X{:.3} Y{:.3} E{:.5} F{:.0}{marker}",
            b.0, b.1, state.e, print_f
        )?;
        state.last = Some(b);
        trail.push(b);
    }
    state.last_print_f = print_f;
    state.wipe = trail.into_iter().rev().collect();
    Ok(())
}

fn xy(p: Point) -> (f64, f64) {
    (unscale(p.x), unscale(p.y))
}

/// Count layer-change comments without double-counting `; CHANGE_LAYER` + `;LAYER:`.
pub fn layer_stats(gcode: &str) -> LayerStats {
    let report = parse_gcode(gcode);
    LayerStats {
        layer_comments: report.layer_changes,
        unique_z: report.unique_z,
    }
}

#[derive(Debug, Clone, Copy)]
pub struct LayerStats {
    pub layer_comments: usize,
    pub unique_z: usize,
}

/// Structured view of G-code for comparing the rewrite to C++ Bambu Studio.
#[derive(Debug, Clone)]
pub struct GcodeReport {
    pub layer_changes: usize,
    pub unique_z: usize,
    pub z_min: f64,
    pub z_max: f64,
    pub max_e: f64,
    pub total_layer_number: Option<u32>,
    pub features: BTreeSet<String>,
    pub estimated_seconds: Option<f64>,
    pub filament_g: Option<f64>,
}

pub fn parse_gcode(gcode: &str) -> GcodeReport {
    let mut change_layer = 0usize;
    let mut layer_colon = 0usize;
    let mut layer_z = Vec::new();
    let mut pending_layer_z: Option<f64> = None;
    let mut in_layer_header = false;
    let mut max_e = 0.0_f64;
    let mut features = BTreeSet::new();
    let mut total_layer_number = None;
    let mut max_z_height = None;
    let mut estimated_seconds = None;
    let mut filament_g = None;
    for line in gcode.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("; CHANGE_LAYER") || trimmed == ";CHANGE_LAYER" {
            if let Some(z) = pending_layer_z.take() {
                layer_z.push(z);
            }
            change_layer += 1;
            in_layer_header = true;
            continue;
        }
        if trimmed.starts_with(";LAYER:") {
            if change_layer == 0 && pending_layer_z.is_none() && !in_layer_header {
                in_layer_header = true;
            }
            layer_colon += 1;
        }
        if let Some(rest) = trimmed.strip_prefix("; total layer number:") {
            if let Ok(n) = rest.trim().parse::<u32>() {
                total_layer_number = Some(n);
            }
        }
        if let Some(rest) = trimmed.strip_prefix("; max_z_height:") {
            if let Ok(z) = rest.trim().parse::<f64>() {
                max_z_height = Some(z);
            }
        }
        if let Some(rest) = trimmed.strip_prefix("; model printing time:") {
            if let Some((clock, _)) = rest.split_once(';') {
                estimated_seconds = parse_time_dhms(clock.trim());
            }
        }
        if let Some(rest) = trimmed.strip_prefix("; total filament weight [g]") {
            let value = rest.trim().trim_start_matches(':').trim();
            if let Ok(g) = value.split(',').next().unwrap_or("").trim().parse::<f64>() {
                filament_g = Some(g);
            }
        }
        if let Some(rest) = trimmed
            .strip_prefix("; FEATURE:")
            .or_else(|| trimmed.strip_prefix(";FEATURE:"))
        {
            if let Some(z) = pending_layer_z.take() {
                layer_z.push(z);
            }
            in_layer_header = false;
            features.insert(rest.trim().to_string());
        }
        if in_layer_header {
            if let Some(z) = parse_g1_z(trimmed) {
                pending_layer_z = Some(z);
            }
        }
        if let Some(e) = parse_axis_g1(trimmed, b'E') {
            if e > max_e {
                max_e = e;
            }
        }
    }
    if let Some(z) = pending_layer_z {
        layer_z.push(z);
    }
    let layer_changes = if change_layer > 0 {
        change_layer
    } else {
        layer_colon
    };
    let z_min = layer_z.iter().copied().fold(f64::INFINITY, f64::min);
    let z_max =
        max_z_height.unwrap_or_else(|| layer_z.iter().copied().fold(f64::NEG_INFINITY, f64::max));
    GcodeReport {
        layer_changes,
        unique_z: layer_z.len(),
        z_min: if z_min.is_finite() { z_min } else { 0.0 },
        z_max: if z_max.is_finite() { z_max } else { 0.0 },
        max_e,
        total_layer_number,
        features,
        estimated_seconds,
        filament_g,
    }
}

/// Key/value pairs from C++ `; CONFIG_BLOCK` comments (`; wall_loops = 2`).
pub fn parse_config_comments(gcode: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for line in gcode.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("; ") else {
            continue;
        };
        if rest.starts_with("FEATURE:") || rest.starts_with("CHANGE_LAYER") {
            continue;
        }
        let Some((key, value)) = rest.split_once(" = ") else {
            continue;
        };
        if key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            out.insert(key.to_string(), value.to_string());
        }
    }
    out
}

/// Compare rewrite G-code to C++ Bambu Studio on geometry-level signals.
pub fn assert_matches_cpp(ours: &GcodeReport, cpp: &GcodeReport) {
    let cpp_layers = cpp
        .total_layer_number
        .map(|n| n as usize)
        .unwrap_or(cpp.layer_changes);
    let delta = ours.layer_changes.abs_diff(cpp_layers);
    assert!(
        delta <= 5,
        "layer count diverged: rust={} cpp={} (CHANGE_LAYER={}, header={:?}) ours={ours:?} cpp={cpp:?}",
        ours.layer_changes,
        cpp_layers,
        cpp.layer_changes,
        cpp.total_layer_number
    );
    assert!(
        (ours.z_max - cpp.z_max).abs() <= 0.6,
        "max Z diverged: rust={} cpp={}",
        ours.z_max,
        cpp.z_max
    );
    for role in [
        "Outer wall",
        "Inner wall",
        "Sparse infill",
        "Bottom surface",
        "Top surface",
        "Internal solid infill",
    ] {
        assert!(
            ours.features.contains(role),
            "rewrite missing FEATURE {role}: {:?}",
            ours.features
        );
        assert!(
            cpp.features.contains(role),
            "C++ Bambu Studio missing FEATURE {role}: {:?}",
            cpp.features
        );
    }
    assert!(
        ours.max_e > 0.0,
        "rewrite G-code has no extrusion (max E={})",
        ours.max_e
    );
    assert!(
        cpp.max_e > 0.0 || cpp.features.iter().any(|f| f != "Custom" && f != "Travel"),
        "C++ G-code has no extrusion (max E={}, features={:?})",
        cpp.max_e,
        cpp.features
    );
}

fn parse_axis_g1(line: &str, axis: u8) -> Option<f64> {
    let upper = line.to_ascii_uppercase();
    if !(upper.starts_with("G1") || upper.starts_with("G0")) {
        return None;
    }
    parse_axis(&upper, axis)
}

fn parse_axis(upper: &str, axis: u8) -> Option<f64> {
    let bytes = upper.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == axis && (i == 0 || bytes[i - 1].is_ascii_whitespace()) {
            let rest = &upper[i + 1..];
            let num: String = rest
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.' || *c == '-')
                .collect();
            if let Ok(v) = num.parse::<f64>() {
                return Some(v);
            }
        }
        i += 1;
    }
    None
}

fn parse_g1_z(line: &str) -> Option<f64> {
    parse_axis_g1(line, b'Z')
}

fn parse_time_dhms(text: &str) -> Option<f64> {
    let mut total = 0.0_f64;
    let mut found = false;
    for token in text.split_whitespace() {
        if let Some(n) = token.strip_suffix('d') {
            total += n.parse::<f64>().ok()? * 86400.0;
            found = true;
        } else if let Some(n) = token.strip_suffix('h') {
            total += n.parse::<f64>().ok()? * 3600.0;
            found = true;
        } else if let Some(n) = token.strip_suffix('m') {
            total += n.parse::<f64>().ok()? * 60.0;
            found = true;
        } else if let Some(n) = token.strip_suffix('s') {
            total += n.parse::<f64>().ok()?;
            found = true;
        }
    }
    found.then_some(total)
}

#[cfg(test)]
mod tests {
    use super::*;
    use bambu_geom::TriangleMesh;
    use bambu_slicer::slice_mesh;

    #[test]
    fn cube_gcode_has_layers() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let stats = layer_stats(&gcode);
        assert!(stats.layer_comments >= 90, "{stats:?}");
        assert!(gcode.contains("G1 X"));
        assert!(gcode.contains("; FEATURE: Outer wall"));
        assert!(gcode.contains("; FEATURE: Sparse infill"));
        assert!(gcode.contains("; FEATURE: Skirt"));
        assert!(gcode.contains("; FEATURE: Bottom surface"));
        assert!(gcode.contains("; FEATURE: Top surface"));
        assert!(gcode.contains("; FEATURE: Internal solid infill"));
        assert!(!gcode.contains("; FEATURE: Ironing"));
        assert!(gcode.contains("; CHANGE_LAYER"));
        let report = parse_gcode(&gcode);
        assert_eq!(report.layer_changes, stats.layer_comments);
        assert!(report.features.contains("Outer wall"));
    }

    #[test]
    fn cube_gcode_has_time_and_filament_estimate() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; model printing time:"));
        assert!(gcode.contains("; total filament weight [g] :"));
        assert!(gcode.contains("; total filament length [mm] :"));
        let report = parse_gcode(&gcode);
        let seconds = report.estimated_seconds.expect("estimated time");
        assert!(
            (60.0..7200.0).contains(&seconds),
            "20 mm cube estimate out of range: {seconds}s"
        );
        let grams = report.filament_g.expect("filament g");
        assert!(
            (1.0..40.0).contains(&grams),
            "20 mm cube filament out of range: {grams}g"
        );
        let processed = process_gcode(&gcode, &settings);
        assert!(processed.move_count > 100);
        assert!((processed.filament_g - grams).abs() < 0.02);
    }

    #[test]
    fn cube_gcode_z_is_print_z() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("G1 Z0.200 F600"));
        assert!(gcode.contains("; max_z_height: 20.00"));
        let report = parse_gcode(&gcode);
        assert!((report.z_min - 0.2).abs() < 1e-6, "z_min={}", report.z_min);
        assert!((report.z_max - 20.0).abs() < 0.05, "z_max={}", report.z_max);
    }

    #[test]
    fn cube_gcode_raft_lifts_object() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.raft_layers = 2;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Support"));
        assert!(gcode.contains("; FEATURE: Support interface"));
        assert!(gcode.contains("G1 Z0.200 F600"));
        assert!(gcode.contains("G1 Z0.800 F600"));
        assert!(gcode.contains("; max_z_height: 20.60"));
        let report = parse_gcode(&gcode);
        assert!((report.z_min - 0.2).abs() < 1e-6, "z_min={}", report.z_min);
        assert!((report.z_max - 20.6).abs() < 0.05, "z_max={}", report.z_max);
    }

    #[test]
    fn parse_does_not_double_count_layer_markers() {
        let gcode = "; CHANGE_LAYER\n;LAYER:0\nG1 Z0.200\n; FEATURE: Outer wall\nG1 X1 Y1 E0.1\n; CHANGE_LAYER\n;LAYER:1\nG1 Z0.400\n";
        let report = parse_gcode(gcode);
        assert_eq!(report.layer_changes, 2);
        assert_eq!(layer_stats(gcode).layer_comments, 2);
        assert!((report.z_max - 0.4).abs() < 1e-9);
    }

    #[test]
    fn cube_bbl_gcode_has_brim_not_skirt() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::bbl_0_20();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Brim"));
        assert!(!gcode.contains("; FEATURE: Skirt"));
        let stats = layer_stats(&gcode);
        assert!((90..=105).contains(&stats.layer_comments), "{stats:?}");
    }

    #[test]
    fn table_gcode_has_support() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.enable_support = true;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains("; FEATURE: Support") || gcode.contains("; FEATURE: Support interface")
        );
    }

    #[test]
    fn support_interface_uses_interface_speed() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.enable_support = true;
        settings.support_speed_mm_s = 40.0;
        settings.support_interface_speed_mm_s = 80.0;
        settings.first_layer_speed_mm_s = 20.0;
        settings.first_layer_infill_speed_mm_s = 20.0;
        settings.infill_speed_mm_s = 90.0;
        settings.solid_infill_speed_mm_s = 90.0;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        assert!(sliced.layers.iter().any(|l| !l.support.is_empty()));
        assert!(sliced
            .layers
            .iter()
            .any(|l| !l.support_interface.is_empty()));
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Support"));
        assert!(gcode.contains("; FEATURE: Support interface"));
        assert!(gcode.contains(" F2400"), "support 40 mm/s");
        assert!(gcode.contains(" F4800"), "support interface 80 mm/s");
    }

    #[test]
    fn cube_ironing_gcode_feature() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.ironing_type = bambu_config::IroningType::TopSurfaces;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Ironing"));
        let report = parse_gcode(&gcode);
        assert!(report.features.contains("Ironing"));
    }

    #[test]
    fn cube_has_no_overhang_wall_feature() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(!gcode.contains("; FEATURE: Overhang wall"));
    }

    #[test]
    fn overhang_table_slows_unsupported_walls() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.overhang_speed_mm_s = 25.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Overhang wall"));
        assert!(gcode.contains(" F1500\n") || gcode.contains(" F1500"));
        let report = parse_gcode(&gcode);
        assert!(report.features.contains("Overhang wall"));
    }

    #[test]
    fn bbl_inner_walls_faster_than_outer() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains(" F12000"), "outer walls should use 200 mm/s");
        assert!(gcode.contains(" F18000"), "inner walls should use 300 mm/s");
    }

    #[test]
    fn volumetric_cap_slows_bbl_walls() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.slow_down_for_layer_cooling = false;
        let mm3 = settings.line_width_mm * settings.layer_height_mm * settings.flow_ratio;
        let cap_f = settings.cap_extrude_feed_mm_min(12_000.0, mm3);
        assert!(cap_f < 12_000.0, "12 mm³/s should cap 200 mm/s walls");
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let token = format!(" F{cap_f:.0}");
        assert!(
            gcode.contains(&token),
            "expected capped feed {token} in gcode"
        );
        assert!(
            !gcode.contains(" F18000"),
            "inner 300 mm/s should not survive the volumetric cap"
        );
    }

    #[test]
    fn first_layer_uses_initial_speed() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.first_layer_speed_mm_s = 20.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains(" F1200"), "first layer 20 mm/s");
        assert!(gcode.contains(" F3000"), "later walls 50 mm/s");
    }

    #[test]
    fn bridge_uses_bridge_speed() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.enable_support = false;
        settings.infill_pattern = bambu_config::InfillPattern::Rectilinear;
        settings.bridge_speed_mm_s = 35.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        assert!(sliced.layers.iter().any(|l| !l.bridge.is_empty()));
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Bridge"));
        assert!(gcode.contains(" F2100"), "bridge 35 mm/s");
    }

    #[test]
    fn top_surface_uses_top_speed() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.top_surface_speed_mm_s = 40.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Top surface"));
        assert!(gcode.contains(" F2400"), "top 40 mm/s");
    }

    #[test]
    fn small_perimeter_slows_tiny_walls() {
        let mesh = TriangleMesh::cube(4.0);
        let mut settings = SliceSettings::default();
        settings.small_perimeter_threshold_mm = 6.0;
        settings.small_perimeter_speed = 50.0;
        settings.small_perimeter_speed_is_percent = true;
        settings.skirt_loops = 0;
        settings.brim_width_mm = 0.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains(" F1500"),
            "later walls should be 50% of 50 mm/s"
        );
        assert!(
            gcode.contains(" F3000"),
            "first layer keeps initial_layer_speed"
        );
    }

    #[test]
    fn small_perimeter_skips_when_threshold_zero() {
        let mesh = TriangleMesh::cube(4.0);
        let mut settings = SliceSettings::default();
        settings.small_perimeter_threshold_mm = 0.0;
        settings.skirt_loops = 0;
        settings.brim_width_mm = 0.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains(" F3000"), "walls stay at 50 mm/s");
        assert!(
            !gcode.contains(" F1500"),
            "threshold 0 disables small-perimeter slowdown"
        );
    }

    #[test]
    fn small_perimeter_skips_large_loops() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.small_perimeter_threshold_mm = 6.5;
        settings.small_perimeter_speed = 50.0;
        settings.small_perimeter_speed_is_percent = true;
        settings.skirt_loops = 0;
        settings.brim_width_mm = 0.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            !gcode.contains(" F1500"),
            "20 mm cube walls are larger than a 6.5 mm radius"
        );
    }

    #[test]
    fn flow_ratio_scales_extrusion() {
        let mesh = TriangleMesh::cube(20.0);
        let mut full = SliceSettings::default();
        full.flow_ratio = 1.0;
        let sliced = slice_mesh(&mesh, &full).unwrap();
        let e_full = parse_gcode(&write_gcode(&full, &sliced).unwrap()).max_e;
        let mut scaled = full.clone();
        scaled.flow_ratio = 0.98;
        let e_scaled = parse_gcode(&write_gcode(&scaled, &sliced).unwrap()).max_e;
        assert!(e_full > 0.0);
        assert!((e_scaled / e_full - 0.98).abs() < 1e-6);
    }

    #[test]
    fn layer_cooling_slows_short_bbl_layers() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let fast_inner = gcode.lines().any(|line| {
            line.contains(" F18000") && !line.contains("_WIPE") && !line.contains("retract")
        });
        assert!(
            !fast_inner,
            "300 mm/s inner walls should be stretched for layer cooling"
        );
    }

    #[test]
    fn pla_emits_part_fan_after_first_layer() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::bbl_0_20();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("M106 S0\n"), "first layer fan off");
        assert!(gcode.contains("M106 S255\n"), "later layers full PLA fan");
        let first_fan = gcode.find("M106 S0\n").expect("closed fan");
        let full_fan = gcode.find("M106 S255\n").expect("full fan");
        assert!(first_fan < full_fan);
    }

    #[test]
    fn thin_wall_emits_gap_infill() {
        let mesh = TriangleMesh::box_mm(0.7, 20.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.wall_loops = 2;
        settings.gap_infill_speed_mm_s = 45.0;
        settings.first_layer_speed_mm_s = 20.0;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        assert!(sliced.layers.iter().any(|l| !l.gap_infill.is_empty()));
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Gap infill"));
        assert!(gcode.contains(" F2700"), "gap infill 45 mm/s");
    }

    #[test]
    fn default_cube_closes_fan_on_layer_zero() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("M106 S0\n"));
        assert!(gcode.contains("M106 S"));
    }

    #[test]
    fn overhang_table_boosts_part_fan() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.enable_support = false;
        settings.fan_min_speed = 20;
        settings.fan_max_speed = 20;
        settings.close_fan_the_first_x_layers = 0;
        settings.reduce_fan_stop_start_freq = true;
        settings.overhang_fan_speed = 100;
        settings.overhang_fan_threshold = bambu_config::OverhangFanThreshold::Bridge;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Overhang wall") || gcode.contains("; FEATURE: Bridge"));
        assert!(!gcode.contains(";_OVERHANG_FAN"));
        assert!(gcode.contains("M106 S51\n"), "layer fan 20%\n{gcode}");
        assert!(gcode.contains("M106 S255\n"), "overhang fan 100%");
    }

    #[test]
    fn ironing_uses_ironing_fan_speed() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.ironing_type = bambu_config::IroningType::TopSurfaces;
        settings.fan_min_speed = 100;
        settings.fan_max_speed = 100;
        settings.close_fan_the_first_x_layers = 1;
        settings.reduce_fan_stop_start_freq = true;
        settings.ironing_fan_speed = 40;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Ironing"));
        assert!(!gcode.contains(";_IRONING_FAN"));
        assert!(gcode.contains("M106 S102\n"), "ironing 40%\n{gcode}");
        assert!(gcode.contains("M106 S255\n"), "layer 100%");
    }

    #[test]
    fn long_travel_emits_retract_and_unretract() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.wipe = false;
        settings.retract_when_changing_layer = false;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; retract"), "{gcode}");
        assert!(gcode.contains("; unretract"));
        assert!(
            gcode.contains("G1 E") && gcode.contains(" F1800"),
            "30 mm/s retract"
        );
        assert!(!gcode.contains("; WIPE_START"));
    }

    #[test]
    fn short_travel_skips_retract() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.retraction_minimum_travel_mm = 1.0e6;
        settings.retract_when_changing_layer = false;
        settings.wipe = false;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(!gcode.contains("; retract"), "{gcode}");
        assert!(!gcode.contains("; unretract"));
    }

    #[test]
    fn zero_retract_length_disables() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.retraction_length_mm = 0.0;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(!gcode.contains("; retract"));
        assert!(!gcode.contains("; WIPE_START"));
    }

    #[test]
    fn bbl_wipe_uses_reverse_path() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; WIPE_START"));
        assert!(gcode.contains("; WIPE_END"));
        assert!(gcode.contains(";_WIPE"));
        assert!(gcode.contains("; unretract"));
        let start = gcode.find("; WIPE_START").unwrap();
        let end = gcode.find("; WIPE_END").unwrap();
        assert!(start < end);
        let wipe = &gcode[start..end];
        assert!(wipe.contains("G1 X"), "wipe travels along the last path");
    }

    #[test]
    fn h2c_spiral_hops_on_travel() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("G17"), "{gcode}");
        assert!(gcode.contains("; spiral lift Z"));
        assert!(gcode.contains("; restore layer Z"));
        assert!(gcode.contains("G2 Z") && gcode.contains(" P1 F"));
        let lines: Vec<&str> = gcode.lines().collect();
        assert!(
            lines
                .windows(2)
                .any(|w| { w[0].contains("; spiral lift Z") && w[1].starts_with("G0 X") }),
            "lazy spiral should sit on the following XY travel\n{gcode}"
        );
        let mut saw_perp = false;
        for line in &lines {
            if !line.contains("; spiral lift Z") {
                continue;
            }
            let upper = line.to_ascii_uppercase();
            let i = parse_axis(&upper, b'I').unwrap_or(0.0);
            let j = parse_axis(&upper, b'J').unwrap_or(0.0);
            if j.abs() > 1e-6 {
                saw_perp = true;
            }
            assert!(
                (i * i + j * j).sqrt() > 0.5,
                "spiral radius should match 0.4 mm hop\n{line}"
            );
        }
        assert!(
            saw_perp,
            "lazy spiral I/J should follow travel, not +X only\n{gcode}"
        );
    }

    #[test]
    fn default_cube_skips_z_hop() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.wipe = false;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(!gcode.contains("; spiral lift Z"));
        assert!(!gcode.contains("; normal lift Z"));
        assert!(!gcode.contains("; restore layer Z"));
    }

    #[test]
    fn h2c_emits_auxiliary_fan() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains("M106 P2 S0\n"),
            "closed aux on first layers\n{gcode}"
        );
        assert!(
            gcode.contains("M106 P2 S191\n"),
            "H2C PLA 75% aux fan\n{gcode}"
        );
        assert!(!gcode.contains("M106 P3"), "filtration off on Generic PLA");
    }

    #[test]
    fn exhaust_fan_when_filtration_enabled() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::default();
        settings.support_air_filtration = true;
        settings.activate_air_filtration = true;
        settings.during_print_exhaust_fan_speed = 70;
        settings.complete_print_exhaust_fan_speed = 80;
        settings.slow_down_for_layer_cooling = false;
        settings.wipe = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains("M106 P3 S178\n"),
            "70% during print\n{gcode}"
        );
        assert!(gcode.contains("M106 P3 S204\n"), "80% after print\n{gcode}");
        let start = gcode.find("M106 P3 S178\n").expect("start exhaust");
        let end = gcode.find("M106 P3 S204\n").expect("end exhaust");
        assert!(start < end, "{gcode}");
    }

    #[test]
    fn normal_lift_uses_g1_z() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.z_hop_type = bambu_config::ZHopType::Normal;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; normal lift Z"));
        assert!(!gcode.contains("; spiral lift Z"));
        assert!(gcode.contains("; restore layer Z"));
    }

    #[test]
    fn slope_lift_emits_diagonal() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.z_hop_type = bambu_config::ZHopType::Slope;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; slope lift Z"), "{gcode}");
        assert!(!gcode.contains("; spiral lift Z"));
        assert!(gcode.contains("; restore layer Z"));
    }

    #[test]
    fn spiral_falls_back_when_off_bed() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        settings.bed_min_x = 0.0;
        settings.bed_min_y = 0.0;
        settings.bed_max_x = 0.5;
        settings.bed_max_y = 0.5;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; normal lift Z"), "{gcode}");
        assert!(!gcode.contains("; spiral lift Z"), "{gcode}");
        assert!(gcode.contains("; restore layer Z"));
    }

    #[test]
    fn auto_hop_cube_uses_slope() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.z_hop_type = bambu_config::ZHopType::Auto;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        settings.brim_width_mm = 0.0;
        settings.skirt_loops = 0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; slope lift Z"), "{gcode}");
        assert!(!gcode.contains("; spiral lift Z"), "{gcode}");
        assert!(gcode.contains("; restore layer Z"));
    }

    #[test]
    fn auto_hop_over_air_uses_spiral() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.z_hop_type = bambu_config::ZHopType::Auto;
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        settings.enable_support = false;
        settings.brim_width_mm = 0.0;
        settings.skirt_loops = 0;
        settings.wipe = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains("; spiral lift Z"),
            "travel over the table wing should spiral\n{gcode}"
        );
    }

    #[test]
    fn no_slow_down_keeps_outer_wall_feed() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.no_slow_down_for_cooling_on_outwalls = true;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains("_EXTERNAL_PERIMETER"),
            "outer walls should carry the C++ cooling marker\n{gcode}"
        );
        let outer_kept = gcode
            .lines()
            .any(|line| line.contains("_EXTERNAL_PERIMETER") && line.contains(" F12000"));
        assert!(
            outer_kept,
            "200 mm/s outer walls should not be stretched\n{gcode}"
        );
        let fast_inner = gcode.lines().any(|line| {
            line.contains(" F18000") && !line.contains("_WIPE") && !line.contains("retract")
        });
        assert!(
            !fast_inner,
            "inner walls should still stretch for layer cooling"
        );
    }

    #[test]
    fn h2c_emits_role_accelerations() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(
            gcode.contains("M204 P500 ; adjust acceleration"),
            "first layer print 500\n{gcode}"
        );
        assert!(
            gcode.contains("M204 P5000 ; adjust acceleration"),
            "outer wall 5000\n{gcode}"
        );
        assert!(
            gcode.contains("M204 P6000 ; adjust acceleration"),
            "first-layer travel 6000\n{gcode}"
        );
        assert!(
            gcode.contains("M204 P10000 ; adjust acceleration"),
            "later travel 10000\n{gcode}"
        );
        let first_print = gcode.find("M204 P500 ;").expect("first layer");
        let outer = gcode.find("M204 P5000 ;").expect("outer");
        assert!(first_print < outer, "{gcode}");
    }

    #[test]
    fn h2c_short_travel_to_outer_wall_uses_250() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        settings.retraction_minimum_travel_mm = 100.0;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let layer1 = gcode.find(";LAYER:1").expect("layer 1");
        assert!(
            !gcode[..layer1].contains("M204 P250"),
            "first layer must keep full travel accel\n{}",
            &gcode[..layer1]
        );
        assert!(
            gcode[layer1..].contains("M204 P250 ; adjust acceleration"),
            "short hop to an outer wall should use 250\n{}",
            &gcode[layer1..]
        );
    }

    #[test]
    fn h2c_emits_layer_change_gcode() {
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let n = sliced.layers.len();
        assert!(
            gcode.contains(&format!("; layer num/total_layer_count: 1/{n}")),
            "{gcode}"
        );
        assert!(gcode.contains("M73 L1"), "{gcode}");
        assert!(gcode.contains("M991 S0 P0 ;notify layer change"), "{gcode}");
        assert!(gcode.contains("M73 L2"), "{gcode}");
        assert!(gcode.contains("M991 S0 P1 ;notify layer change"), "{gcode}");
        assert!(gcode.contains("; open powerlost recovery"));
        assert!(gcode.contains("M1003 S1"));
        let layer1 = gcode.find(";LAYER:1").expect("layer 1");
        assert!(
            !gcode[..layer1].contains("M1003 S1"),
            "power-loss recovery opens on the second layer"
        );
        assert!(gcode.contains(";_SET_FAN_SPEED_CHANGING_LAYER"));
    }

    #[test]
    fn default_cube_keeps_generic_marlin_footer() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("G28 X0 Y0"));
        assert!(gcode.contains("M84"));
        assert!(!gcode.contains("; MACHINE_END_GCODE_START"));
        assert!(!gcode.contains(";===== machine: H2C end ====="));
        assert!(gcode.contains("M104 S220") || gcode.contains("M104 S"));
        assert!(gcode.contains("\nG28\n") || gcode.lines().any(|l| l == "G28"));
    }

    #[test]
    fn h2c_emits_machine_end_gcode() {
        let paths = bambu_config::bbl_oracle_paths().expect("upstream BambuStudio profiles");
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        bambu_config::overlay_bbl_profile(&mut settings, &paths.machine).unwrap();
        bambu_config::overlay_bbl_profile(&mut settings, &paths.filament).unwrap();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let z = sliced.layers.last().unwrap().print_z_mm;
        assert!(gcode.contains("; MACHINE_END_GCODE_START"), "{gcode}");
        assert!(gcode.contains(";===== machine: H2C end ====="), "{gcode}");
        assert!(gcode.contains("; filament end gcode"), "{gcode}");
        assert!(gcode.contains("M1003 S0"), "{gcode}");
        assert!(
            gcode.contains(&format!("G1 Z{} F900 ; lower z a little", z + 0.4))
                || gcode.contains(&format!("G1 Z{:.1} F900 ; lower z a little", z + 0.4)),
            "expected first Z park at {}+0.4\n{gcode}",
            z
        );
        assert!(
            gcode.contains("M620.11 P1 I0 B0 E-14 F"),
            "long retract-on-cut branch should expand\n{gcode}"
        );
        assert!(
            !gcode.contains("M620.11 P0 I0 B0 E0"),
            "cut-retract else branch should be skipped\n{gcode}"
        );
        assert!(
            gcode.contains("M620.11 K1 I0 B0 R10 F"),
            "ec retract-on-cut should expand\n{gcode}"
        );
        assert!(
            !gcode.contains("M620.11 K0 I0 B0 R0"),
            "ec retract else branch should be skipped\n{gcode}"
        );
        let park = z + 100.0 - z / 2.0;
        let park_s = if (park - park.round()).abs() < 1e-6 {
            format!("{}", park.round() as i64)
        } else {
            let s = format!("{park:.5}");
            s.trim_end_matches('0').trim_end_matches('.').to_string()
        };
        let end = gcode
            .rfind("; MACHINE_END_GCODE_START")
            .map(|i| &gcode[i..])
            .unwrap_or(&gcode);
        assert!(
            end.contains(&format!("G1 Z{park_s} F600")),
            "expected nested Z park at {park_s} (raw {park})\n{end}"
        );
        assert!(!gcode.contains("G28 X0 Y0"), "{gcode}");
        assert!(!gcode.contains("{if"), "unexpanded if in\n{gcode}");
        assert!(!gcode.contains("{endif}"), "unexpanded endif in\n{gcode}");
        assert!(!gcode.contains("{max_layer_z"), "unexpanded z in\n{gcode}");
    }

    #[test]
    fn h2c_emits_machine_start_gcode() {
        let paths = bambu_config::bbl_oracle_paths().expect("upstream BambuStudio profiles");
        let mesh = TriangleMesh::cube(20.0);
        let mut settings = SliceSettings::bbl_0_20();
        bambu_config::overlay_bbl_profile(&mut settings, &paths.machine).unwrap();
        bambu_config::overlay_bbl_profile(&mut settings, &paths.filament).unwrap();
        settings.filament_max_volumetric_speed_mm3_s = 0.0;
        settings.slow_down_for_layer_cooling = false;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let header_end = gcode.find("; CHANGE_LAYER").expect("layers");
        let header = &gcode[..header_end];
        assert!(
            header.contains(";===== machine: H2C ========================="),
            "{header}"
        );
        assert!(header.contains("; MACHINE_START_GCODE_END"), "{header}");
        assert!(header.contains("G28 X T300"), "{header}");
        assert!(
            header.contains("M145 P0"),
            "PLA uses cooling airduct\n{header}"
        );
        assert!(
            header.contains("M142 P1 R30 S40 T45"),
            "PLA 0.4 chamber autocool\n{header}"
        );
        assert!(header.contains("; filament start gcode"), "{header}");
        assert!(header.contains(";VT0 H0"), "{header}");
        assert!(
            header.contains("M82 ; use absolute distances for extrusion"),
            "{header}"
        );
        assert!(
            !header.lines().any(|l| l == "G28"),
            "generic home should be skipped\n{header}"
        );
        assert!(!header.contains("{if"), "unexpanded if in\n{header}");
        assert!(!header.contains("{endif}"), "unexpanded endif in\n{header}");
        assert!(!header.contains("{filament_type"), "{header}");
        assert!(!header.contains("{first_layer_print_min"), "{header}");
        assert!(!header.contains("{+0.0}"), "{header}");
    }

    #[test]
    fn default_cube_skips_layer_change_gcode() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(!gcode.contains("M991 S0 P"));
        assert!(!gcode.contains("M1003 S1"));
    }
}
