#![forbid(unsafe_code)]

use std::fmt::Write as _;

use bambu_config::{Flow, SliceSettings};
use bambu_geom::{unscale, Point, Polyline};
use bambu_slicer::SliceResult;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum GcodeError {
    #[error("format: {0}")]
    Format(#[from] std::fmt::Error),
}

pub fn write_gcode(settings: &SliceSettings, sliced: &SliceResult) -> Result<String, GcodeError> {
    let mut out = String::new();
    writeln!(out, "; generated by bambu-cli (safe-Rust rewrite)")?;
    writeln!(out, ";LAYER_COUNT:{}", sliced.layers.len())?;
    writeln!(out, "M104 S{}", settings.temperature_c)?;
    writeln!(out, "M140 S{}", settings.bed_temperature_c)?;
    writeln!(out, "G90")?;
    writeln!(out, "G21")?;
    writeln!(out, "G28")?;
    writeln!(out, "M109 S{}", settings.temperature_c)?;
    writeln!(out, "M190 S{}", settings.bed_temperature_c)?;
    writeln!(out, "G92 E0")?;

    let travel_f = settings.travel_speed_mm_s * 60.0;
    let wall_f = settings.print_speed_mm_s * 60.0;
    let infill_f = settings.infill_speed_mm_s * 60.0;
    let support_f = settings.support_speed_mm_s * 60.0;

    let mut e = 0.0_f64;
    let mut last: Option<(f64, f64)> = None;
    for layer in &sliced.layers {
        writeln!(out, ";LAYER:{}", layer.index)?;
        writeln!(out, "G1 Z{:.3} F600", layer.z_mm)?;
        let flow = Flow::from_settings(settings, settings.layer_height_at(layer.index));
        let e_per_mm = flow.e_per_mm();

        if !layer.skirt.is_empty() {
            writeln!(out, "; FEATURE: Skirt")?;
            emit_paths(
                &mut out,
                &layer.skirt,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.brim.is_empty() {
            writeln!(out, "; FEATURE: Brim")?;
            emit_paths(
                &mut out,
                &layer.brim,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.support.is_empty() {
            writeln!(out, "; FEATURE: Support")?;
            emit_paths(
                &mut out,
                &layer.support,
                false,
                &mut e,
                e_per_mm,
                support_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.support_interface.is_empty() {
            writeln!(out, "; FEATURE: Support interface")?;
            emit_paths(
                &mut out,
                &layer.support_interface,
                false,
                &mut e,
                e_per_mm,
                support_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.outer_walls.is_empty() {
            writeln!(out, "; FEATURE: Outer wall")?;
            emit_paths(
                &mut out,
                &layer.outer_walls,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.inner_walls.is_empty() {
            writeln!(out, "; FEATURE: Inner wall")?;
            emit_paths(
                &mut out,
                &layer.inner_walls,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.infill.is_empty() {
            writeln!(out, "; FEATURE: Sparse infill")?;
            emit_paths(
                &mut out,
                &layer.infill,
                false,
                &mut e,
                e_per_mm,
                infill_f,
                travel_f,
                &mut last,
            )?;
        }
    }

    writeln!(out, "M104 S0")?;
    writeln!(out, "M140 S0")?;
    writeln!(out, "G28 X0 Y0")?;
    writeln!(out, "M84")?;
    Ok(out)
}

#[allow(clippy::too_many_arguments)]
fn emit_paths(
    out: &mut String,
    paths: &[Polyline],
    closed: bool,
    e: &mut f64,
    e_per_mm: f64,
    print_f: f64,
    travel_f: f64,
    last: &mut Option<(f64, f64)>,
) -> Result<(), GcodeError> {
    for path in paths {
        if path.len() < 2 {
            continue;
        }
        let pts: Vec<(f64, f64)> = path.iter().copied().map(xy).collect();
        let start = pts[0];
        writeln!(out, "G0 X{:.3} Y{:.3} F{:.0}", start.0, start.1, travel_f)?;
        *last = Some(start);
        let n = pts.len();
        let end = if closed { n } else { n - 1 };
        for i in 0..end {
            let a = pts[i];
            let b = pts[(i + 1) % n];
            let dist = ((b.0 - a.0).powi(2) + (b.1 - a.1).powi(2)).sqrt();
            *e += dist * e_per_mm;
            writeln!(
                out,
                "G1 X{:.3} Y{:.3} E{:.5} F{:.0}",
                b.0, b.1, *e, print_f
            )?;
            *last = Some(b);
        }
    }
    Ok(())
}

fn xy(p: Point) -> (f64, f64) {
    (unscale(p.x), unscale(p.y))
}

/// Count `;LAYER:` markers (our dialect) and unique `G1 Z` heights.
pub fn layer_stats(gcode: &str) -> LayerStats {
    let mut layer_comments = 0usize;
    let mut z_values = Vec::new();
    for line in gcode.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with(";LAYER:") || trimmed.starts_with("; CHANGE_LAYER") {
            layer_comments += 1;
        }
        if let Some(z) = parse_g1_z(trimmed) {
            if z_values.last().copied() != Some(z) {
                z_values.push(z);
            }
        }
    }
    LayerStats {
        layer_comments,
        unique_z: z_values.len(),
    }
}

#[derive(Debug, Clone, Copy)]
pub struct LayerStats {
    pub layer_comments: usize,
    pub unique_z: usize,
}

fn parse_g1_z(line: &str) -> Option<f64> {
    let upper = line.to_ascii_uppercase();
    if !(upper.starts_with("G1 ")
        || upper.starts_with("G0 ")
        || upper.starts_with("G1")
        || upper.starts_with("G0"))
    {
        return None;
    }
    let bytes = upper.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == b'Z' {
            let rest = &upper[i + 1..];
            let num: String = rest
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.' || *c == '-')
                .collect();
            if let Ok(v) = num.parse::<f64>() {
                return Some(v);
            }
        }
        i += 1;
    }
    None
}

#[cfg(test)]
mod tests {
    use super::*;
    use bambu_geom::TriangleMesh;
    use bambu_slicer::slice_mesh;

    #[test]
    fn cube_gcode_has_layers() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let stats = layer_stats(&gcode);
        assert!(stats.layer_comments >= 90, "{stats:?}");
        assert!(gcode.contains("G1 X"));
        assert!(gcode.contains("; FEATURE: Outer wall"));
        assert!(gcode.contains("; FEATURE: Sparse infill"));
        assert!(gcode.contains("; FEATURE: Skirt"));
    }

    #[test]
    fn table_gcode_has_support() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.enable_support = true;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Support") || gcode.contains("; FEATURE: Support interface"));
    }
}
