#![forbid(unsafe_code)]

use std::collections::{BTreeMap, BTreeSet};
use std::fmt::Write as _;

use bambu_config::{Flow, SliceSettings};
use bambu_geom::{unscale, Point, Polyline};
use bambu_slicer::SliceResult;
use thiserror::Error;

#[derive(Debug, Error)]
pub enum GcodeError {
    #[error("format: {0}")]
    Format(#[from] std::fmt::Error),
}

pub fn write_gcode(settings: &SliceSettings, sliced: &SliceResult) -> Result<String, GcodeError> {
    let mut out = String::new();
    writeln!(out, "; generated by bambu-cli (safe-Rust rewrite)")?;
    writeln!(out, ";LAYER_COUNT:{}", sliced.layers.len())?;
    if let Some(last) = sliced.layers.last() {
        writeln!(out, "; max_z_height: {:.2}", last.z_mm)?;
    }
    writeln!(out, "M104 S{}", settings.temperature_c)?;
    writeln!(out, "M140 S{}", settings.bed_temperature_c)?;
    writeln!(out, "G90")?;
    writeln!(out, "G21")?;
    writeln!(out, "G28")?;
    writeln!(out, "M109 S{}", settings.temperature_c)?;
    writeln!(out, "M190 S{}", settings.bed_temperature_c)?;
    writeln!(out, "G92 E0")?;

    let travel_f = settings.travel_speed_mm_s * 60.0;
    let wall_f = settings.print_speed_mm_s * 60.0;
    let infill_f = settings.infill_speed_mm_s * 60.0;
    let solid_f = settings.solid_infill_speed_mm_s * 60.0;
    let support_f = settings.support_speed_mm_s * 60.0;

    let mut e = 0.0_f64;
    let mut last: Option<(f64, f64)> = None;
    for layer in &sliced.layers {
        writeln!(out, "; CHANGE_LAYER")?;
        writeln!(out, ";LAYER:{}", layer.index)?;
        writeln!(
            out,
            "; LAYER_HEIGHT:{}",
            settings.layer_height_at(layer.index)
        )?;
        writeln!(out, "G1 Z{:.3} F600", layer.z_mm)?;
        let flow = Flow::from_settings(settings, settings.layer_height_at(layer.index));
        let e_per_mm = flow.e_per_mm();

        if !layer.skirt.is_empty() {
            writeln!(out, "; FEATURE: Skirt")?;
            emit_paths(
                &mut out,
                &layer.skirt,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.brim.is_empty() {
            writeln!(out, "; FEATURE: Brim")?;
            emit_paths(
                &mut out,
                &layer.brim,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.support.is_empty() {
            writeln!(out, "; FEATURE: Support")?;
            emit_paths(
                &mut out,
                &layer.support,
                false,
                &mut e,
                e_per_mm,
                support_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.support_interface.is_empty() {
            writeln!(out, "; FEATURE: Support interface")?;
            emit_paths(
                &mut out,
                &layer.support_interface,
                false,
                &mut e,
                e_per_mm,
                support_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.outer_walls.is_empty() {
            writeln!(out, "; FEATURE: Outer wall")?;
            emit_paths(
                &mut out,
                &layer.outer_walls,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.inner_walls.is_empty() {
            writeln!(out, "; FEATURE: Inner wall")?;
            emit_paths(
                &mut out,
                &layer.inner_walls,
                true,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.infill.is_empty() {
            writeln!(out, "; FEATURE: Sparse infill")?;
            emit_paths(
                &mut out,
                &layer.infill,
                false,
                &mut e,
                e_per_mm,
                infill_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.solid_infill.is_empty() {
            writeln!(out, "; FEATURE: Internal solid infill")?;
            emit_paths(
                &mut out,
                &layer.solid_infill,
                false,
                &mut e,
                e_per_mm,
                solid_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.bridge.is_empty() {
            writeln!(out, "; FEATURE: Bridge")?;
            emit_paths(
                &mut out,
                &layer.bridge,
                false,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.bottom_surface.is_empty() {
            writeln!(out, "; FEATURE: Bottom surface")?;
            emit_paths(
                &mut out,
                &layer.bottom_surface,
                false,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
        if !layer.top_surface.is_empty() {
            writeln!(out, "; FEATURE: Top surface")?;
            emit_paths(
                &mut out,
                &layer.top_surface,
                false,
                &mut e,
                e_per_mm,
                wall_f,
                travel_f,
                &mut last,
            )?;
        }
    }

    writeln!(out, "M104 S0")?;
    writeln!(out, "M140 S0")?;
    writeln!(out, "G28 X0 Y0")?;
    writeln!(out, "M84")?;
    Ok(out)
}

#[allow(clippy::too_many_arguments)]
fn emit_paths(
    out: &mut String,
    paths: &[Polyline],
    closed: bool,
    e: &mut f64,
    e_per_mm: f64,
    print_f: f64,
    travel_f: f64,
    last: &mut Option<(f64, f64)>,
) -> Result<(), GcodeError> {
    for path in paths {
        if path.len() < 2 {
            continue;
        }
        let pts: Vec<(f64, f64)> = path.iter().copied().map(xy).collect();
        let start = pts[0];
        writeln!(out, "G0 X{:.3} Y{:.3} F{:.0}", start.0, start.1, travel_f)?;
        *last = Some(start);
        let n = pts.len();
        let end = if closed { n } else { n - 1 };
        for i in 0..end {
            let a = pts[i];
            let b = pts[(i + 1) % n];
            let dist = ((b.0 - a.0).powi(2) + (b.1 - a.1).powi(2)).sqrt();
            *e += dist * e_per_mm;
            writeln!(
                out,
                "G1 X{:.3} Y{:.3} E{:.5} F{:.0}",
                b.0, b.1, *e, print_f
            )?;
            *last = Some(b);
        }
    }
    Ok(())
}

fn xy(p: Point) -> (f64, f64) {
    (unscale(p.x), unscale(p.y))
}

/// Count layer-change comments without double-counting `; CHANGE_LAYER` + `;LAYER:`.
pub fn layer_stats(gcode: &str) -> LayerStats {
    let report = parse_gcode(gcode);
    LayerStats {
        layer_comments: report.layer_changes,
        unique_z: report.unique_z,
    }
}

#[derive(Debug, Clone, Copy)]
pub struct LayerStats {
    pub layer_comments: usize,
    pub unique_z: usize,
}

/// Structured view of G-code for comparing the rewrite to C++ Bambu Studio.
#[derive(Debug, Clone)]
pub struct GcodeReport {
    pub layer_changes: usize,
    pub unique_z: usize,
    pub z_min: f64,
    pub z_max: f64,
    pub max_e: f64,
    pub total_layer_number: Option<u32>,
    pub features: BTreeSet<String>,
}

pub fn parse_gcode(gcode: &str) -> GcodeReport {
    let mut change_layer = 0usize;
    let mut layer_colon = 0usize;
    let mut layer_z = Vec::new();
    let mut pending_layer_z: Option<f64> = None;
    let mut in_layer_header = false;
    let mut max_e = 0.0_f64;
    let mut features = BTreeSet::new();
    let mut total_layer_number = None;
    let mut max_z_height = None;
    for line in gcode.lines() {
        let trimmed = line.trim();
        if trimmed.starts_with("; CHANGE_LAYER") || trimmed == ";CHANGE_LAYER" {
            if let Some(z) = pending_layer_z.take() {
                layer_z.push(z);
            }
            change_layer += 1;
            in_layer_header = true;
            continue;
        }
        if trimmed.starts_with(";LAYER:") {
            if change_layer == 0 && pending_layer_z.is_none() && !in_layer_header {
                in_layer_header = true;
            }
            layer_colon += 1;
        }
        if let Some(rest) = trimmed.strip_prefix("; total layer number:") {
            if let Ok(n) = rest.trim().parse::<u32>() {
                total_layer_number = Some(n);
            }
        }
        if let Some(rest) = trimmed.strip_prefix("; max_z_height:") {
            if let Ok(z) = rest.trim().parse::<f64>() {
                max_z_height = Some(z);
            }
        }
        if let Some(rest) = trimmed
            .strip_prefix("; FEATURE:")
            .or_else(|| trimmed.strip_prefix(";FEATURE:"))
        {
            if let Some(z) = pending_layer_z.take() {
                layer_z.push(z);
            }
            in_layer_header = false;
            features.insert(rest.trim().to_string());
        }
        if in_layer_header {
            if let Some(z) = parse_g1_z(trimmed) {
                pending_layer_z = Some(z);
            }
        }
        if let Some(e) = parse_axis_g1(trimmed, b'E') {
            if e > max_e {
                max_e = e;
            }
        }
    }
    if let Some(z) = pending_layer_z {
        layer_z.push(z);
    }
    let layer_changes = if change_layer > 0 {
        change_layer
    } else {
        layer_colon
    };
    let z_min = layer_z.iter().copied().fold(f64::INFINITY, f64::min);
    let z_max = max_z_height.unwrap_or_else(|| {
        layer_z.iter().copied().fold(f64::NEG_INFINITY, f64::max)
    });
    GcodeReport {
        layer_changes,
        unique_z: layer_z.len(),
        z_min: if z_min.is_finite() { z_min } else { 0.0 },
        z_max: if z_max.is_finite() { z_max } else { 0.0 },
        max_e,
        total_layer_number,
        features,
    }
}

/// Key/value pairs from C++ `; CONFIG_BLOCK` comments (`; wall_loops = 2`).
pub fn parse_config_comments(gcode: &str) -> BTreeMap<String, String> {
    let mut out = BTreeMap::new();
    for line in gcode.lines() {
        let trimmed = line.trim();
        let Some(rest) = trimmed.strip_prefix("; ") else {
            continue;
        };
        if rest.starts_with("FEATURE:") || rest.starts_with("CHANGE_LAYER") {
            continue;
        }
        let Some((key, value)) = rest.split_once(" = ") else {
            continue;
        };
        if key.chars().all(|c| c.is_ascii_alphanumeric() || c == '_') {
            out.insert(key.to_string(), value.to_string());
        }
    }
    out
}

/// Compare rewrite G-code to C++ Bambu Studio on geometry-level signals.
pub fn assert_matches_cpp(ours: &GcodeReport, cpp: &GcodeReport) {
    let cpp_layers = cpp
        .total_layer_number
        .map(|n| n as usize)
        .unwrap_or(cpp.layer_changes);
    let delta = ours.layer_changes.abs_diff(cpp_layers);
    assert!(
        delta <= 5,
        "layer count diverged: rust={} cpp={} (CHANGE_LAYER={}, header={:?}) ours={ours:?} cpp={cpp:?}",
        ours.layer_changes,
        cpp_layers,
        cpp.layer_changes,
        cpp.total_layer_number
    );
    assert!(
        (ours.z_max - cpp.z_max).abs() <= 0.6,
        "max Z diverged: rust={} cpp={}",
        ours.z_max,
        cpp.z_max
    );
    for role in [
        "Outer wall",
        "Inner wall",
        "Sparse infill",
        "Bottom surface",
        "Top surface",
        "Internal solid infill",
    ] {
        assert!(
            ours.features.contains(role),
            "rewrite missing FEATURE {role}: {:?}",
            ours.features
        );
        assert!(
            cpp.features.contains(role),
            "C++ Bambu Studio missing FEATURE {role}: {:?}",
            cpp.features
        );
    }
    assert!(
        ours.max_e > 0.0,
        "rewrite G-code has no extrusion (max E={})",
        ours.max_e
    );
    assert!(
        cpp.max_e > 0.0
            || cpp.features.iter().any(|f| f != "Custom" && f != "Travel"),
        "C++ G-code has no extrusion (max E={}, features={:?})",
        cpp.max_e,
        cpp.features
    );
}

fn parse_axis_g1(line: &str, axis: u8) -> Option<f64> {
    let upper = line.to_ascii_uppercase();
    if !(upper.starts_with("G1") || upper.starts_with("G0")) {
        return None;
    }
    parse_axis(&upper, axis)
}

fn parse_axis(upper: &str, axis: u8) -> Option<f64> {
    let bytes = upper.as_bytes();
    let mut i = 0;
    while i < bytes.len() {
        if bytes[i] == axis && (i == 0 || bytes[i - 1].is_ascii_whitespace()) {
            let rest = &upper[i + 1..];
            let num: String = rest
                .chars()
                .take_while(|c| c.is_ascii_digit() || *c == '.' || *c == '-')
                .collect();
            if let Ok(v) = num.parse::<f64>() {
                return Some(v);
            }
        }
        i += 1;
    }
    None
}

fn parse_g1_z(line: &str) -> Option<f64> {
    parse_axis_g1(line, b'Z')
}

#[cfg(test)]
mod tests {
    use super::*;
    use bambu_geom::TriangleMesh;
    use bambu_slicer::slice_mesh;

    #[test]
    fn cube_gcode_has_layers() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::default();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        let stats = layer_stats(&gcode);
        assert!(stats.layer_comments >= 90, "{stats:?}");
        assert!(gcode.contains("G1 X"));
        assert!(gcode.contains("; FEATURE: Outer wall"));
        assert!(gcode.contains("; FEATURE: Sparse infill"));
        assert!(gcode.contains("; FEATURE: Skirt"));
        assert!(gcode.contains("; FEATURE: Bottom surface"));
        assert!(gcode.contains("; FEATURE: Top surface"));
        assert!(gcode.contains("; FEATURE: Internal solid infill"));
        assert!(gcode.contains("; CHANGE_LAYER"));
        let report = parse_gcode(&gcode);
        assert_eq!(report.layer_changes, stats.layer_comments);
        assert!(report.features.contains("Outer wall"));
    }

    #[test]
    fn parse_does_not_double_count_layer_markers() {
        let gcode = "; CHANGE_LAYER\n;LAYER:0\nG1 Z0.200\n; FEATURE: Outer wall\nG1 X1 Y1 E0.1\n; CHANGE_LAYER\n;LAYER:1\nG1 Z0.400\n";
        let report = parse_gcode(gcode);
        assert_eq!(report.layer_changes, 2);
        assert_eq!(layer_stats(gcode).layer_comments, 2);
        assert!((report.z_max - 0.4).abs() < 1e-9);
    }

    #[test]
    fn cube_bbl_gcode_has_brim_not_skirt() {
        let mesh = TriangleMesh::cube(20.0);
        let settings = SliceSettings::bbl_0_20();
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Brim"));
        assert!(!gcode.contains("; FEATURE: Skirt"));
        let stats = layer_stats(&gcode);
        assert!(
            (90..=105).contains(&stats.layer_comments),
            "{stats:?}"
        );
    }

    #[test]
    fn table_gcode_has_support() {
        let mesh = TriangleMesh::overhang_table(8.0, 8.0, 24.0, 4.0);
        let mut settings = SliceSettings::default();
        settings.enable_support = true;
        let sliced = slice_mesh(&mesh, &settings).unwrap();
        let gcode = write_gcode(&settings, &sliced).unwrap();
        assert!(gcode.contains("; FEATURE: Support") || gcode.contains("; FEATURE: Support interface"));
    }
}
