//! Wayland compositors ignore `winit::Window::set_window_icon`.
//!
//! KWin/Plasma look up `xdg_toplevel.app_id` in a `.desktop` file already on
//! the session `XDG_DATA_*` search path, then load `Icon=` from hicolor. A
//! `cargo run` binary never installs those files, so the placeholder Wayland
//! icon shows in the titlebar and taskbar. Publish an idempotent copy under
//! `$XDG_DATA_HOME` (which KWin already searches) before the window is created.

use std::fs;
use std::io;
use std::path::{Path, PathBuf};
use std::process::{Command, Stdio};
use std::time::{Duration, Instant};

pub const APP_ID: &str = "bambu-studio-rs";

const GENERATED_MARK: &str = "# Generated by bambu-studio-rs; rewritten on launch\n";

const ICON_32: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/icons/hicolor/32x32/apps/bambu-studio-rs.png"
));
const ICON_48: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/icons/hicolor/48x48/apps/bambu-studio-rs.png"
));
const ICON_64: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/icons/hicolor/64x64/apps/bambu-studio-rs.png"
));
const ICON_128: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/icons/hicolor/128x128/apps/bambu-studio-rs.png"
));
const ICON_256: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/icons/hicolor/256x256/apps/bambu-studio-rs.png"
));
const ICON_512: &[u8] = include_bytes!(concat!(
    env!("CARGO_MANIFEST_DIR"),
    "/../../resources/icons/hicolor/512x512/apps/bambu-studio-rs.png"
));

const ICON_SIZES: &[(&str, &[u8])] = &[
    ("32x32", ICON_32),
    ("48x48", ICON_48),
    ("64x64", ICON_64),
    ("128x128", ICON_128),
    ("256x256", ICON_256),
    ("512x512", ICON_512),
];

pub fn publish() {
    let Ok(data_home) = data_home() else {
        return;
    };
    match publish_into(&data_home) {
        Ok(true) => refresh_session_caches(&data_home),
        Ok(false) => {}
        Err(_) => {}
    }
}

fn data_home() -> io::Result<PathBuf> {
    if let Ok(dir) = std::env::var("XDG_DATA_HOME") {
        if !dir.is_empty() {
            return Ok(PathBuf::from(dir));
        }
    }
    let home = std::env::var_os("HOME")
        .ok_or_else(|| io::Error::new(io::ErrorKind::NotFound, "HOME is unset"))?;
    Ok(PathBuf::from(home).join(".local/share"))
}

pub(crate) fn publish_into(data_home: &Path) -> io::Result<bool> {
    let mut changed = false;
    for (size, bytes) in ICON_SIZES {
        let path = data_home
            .join("icons/hicolor")
            .join(size)
            .join("apps")
            .join(format!("{APP_ID}.png"));
        changed |= write_if_changed(&path, bytes)?;
    }
    let pixmap = data_home.join("pixmaps").join(format!("{APP_ID}.png"));
    changed |= write_if_changed(&pixmap, ICON_256)?;

    let icon_path = data_home
        .join("icons/hicolor/256x256/apps")
        .join(format!("{APP_ID}.png"));
    let exec = quote_exec(&std::env::current_exe()?);
    let desktop = desktop_entry(&exec, &icon_path);
    let desktop_path = data_home
        .join("applications")
        .join(format!("{APP_ID}.desktop"));
    changed |= write_desktop(&desktop_path, &desktop)?;
    Ok(changed)
}

fn desktop_entry(exec: &str, icon_path: &Path) -> String {
    format!(
        "\
{GENERATED_MARK}\
[Desktop Entry]\n\
Type=Application\n\
Name=Bambu Studio\n\
GenericName=3D Printing Slicer\n\
Comment=Bambu Studio (Rust rewrite)\n\
Exec={exec}\n\
Icon={icon}\n\
Terminal=false\n\
Categories=Graphics;3DGraphics;Engineering;\n\
StartupWMClass={APP_ID}\n\
StartupNotify=true\n\
SingleMainWindow=true\n\
Keywords=slicer;3D;printing;bambu;\n",
        icon = icon_path.display()
    )
}

fn quote_exec(path: &Path) -> String {
    let raw = path.to_string_lossy();
    if raw
        .bytes()
        .any(|b| matches!(b, b' ' | b'\t' | b'\n' | b'"' | b'\'' | b'\\' | b'$' | b'`'))
    {
        format!("\"{}\"", raw.replace('\\', "\\\\").replace('"', "\\\""))
    } else {
        raw.into_owned()
    }
}

fn write_if_changed(path: &Path, contents: &[u8]) -> io::Result<bool> {
    if path.is_file() && fs::read(path).ok().as_deref() == Some(contents) {
        return Ok(false);
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(true)
}

fn write_desktop(path: &Path, contents: &str) -> io::Result<bool> {
    if path.is_file() {
        let existing = fs::read_to_string(path)?;
        if !existing.contains("# Generated by bambu-studio-rs") {
            return Ok(false);
        }
        if existing == contents {
            return Ok(false);
        }
    }
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(path, contents)?;
    Ok(true)
}

fn refresh_session_caches(data_home: &Path) {
    let hicolor = data_home.join("icons/hicolor");
    for bin in ["gtk-update-icon-cache", "gtk4-update-icon-cache"] {
        let _ = Command::new(bin)
            .args(["-f", "-t"])
            .arg(&hicolor)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status();
    }
    wait_briefly("kbuildsycoca6");
}

fn wait_briefly(bin: &str) {
    let Ok(mut child) = Command::new(bin)
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .spawn()
    else {
        return;
    };
    let deadline = Instant::now() + Duration::from_secs(2);
    loop {
        match child.try_wait() {
            Ok(Some(_)) => return,
            Ok(None) if Instant::now() < deadline => {
                std::thread::sleep(Duration::from_millis(40));
            }
            _ => return,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn publishes_desktop_and_hicolor_icons() {
        let dir = std::env::temp_dir().join(format!(
            "bambu-ui-desktop-{}-{}",
            std::process::id(),
            std::time::SystemTime::now()
                .duration_since(std::time::UNIX_EPOCH)
                .map(|d| d.as_nanos())
                .unwrap_or(0)
        ));
        fs::create_dir_all(&dir).expect("temp data home");
        let changed = publish_into(&dir).expect("publish");
        assert!(changed);

        let desktop_path = dir.join("applications/bambu-studio-rs.desktop");
        let desktop = fs::read_to_string(&desktop_path).expect("desktop");
        assert!(desktop.starts_with(GENERATED_MARK));
        assert!(desktop.contains("StartupWMClass=bambu-studio-rs"));
        assert!(desktop.contains("Icon="));
        let icon = dir.join("icons/hicolor/256x256/apps/bambu-studio-rs.png");
        assert!(icon.is_file());
        assert!(desktop.contains(&icon.display().to_string()));
        assert_eq!(
            fs::read(dir.join("icons/hicolor/32x32/apps/bambu-studio-rs.png")).unwrap(),
            ICON_32
        );
        assert_eq!(
            fs::read(dir.join("pixmaps/bambu-studio-rs.png")).unwrap(),
            ICON_256
        );
        assert!(!publish_into(&dir).expect("second publish"));
        fs::remove_dir_all(&dir).ok();
    }

    #[test]
    fn skips_user_edited_desktop_file() {
        let dir =
            std::env::temp_dir().join(format!("bambu-ui-desktop-skip-{}", std::process::id()));
        let apps = dir.join("applications");
        fs::create_dir_all(&apps).unwrap();
        let path = apps.join("bambu-studio-rs.desktop");
        fs::write(&path, "[Desktop Entry]\nName=Custom\n").unwrap();
        publish_into(&dir).unwrap();
        let kept = fs::read_to_string(&path).unwrap();
        assert_eq!(kept, "[Desktop Entry]\nName=Custom\n");
        fs::remove_dir_all(&dir).ok();
    }
}
