[package]
name = "elysian-gpu"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "wgpu Vulkan viewport and compute slice acceleration"

[lints]
workspace = true

[dependencies]
ab_glyph.workspace = true
elysian-config.workspace = true
elysian-geom.workspace = true
elysian-model.workspace = true
elysian-preview.workspace = true
elysian-slicer.workspace = true
bytemuck.workspace = true
glam.workspace = true
iced.workspace = true
pollster.workspace = true
rayon.workspace = true
thiserror.workspace = true
tracing.workspace = true
wgpu.workspace = true
elysian-wgpu-exp.workspace = true

[dev-dependencies]
naga = { version = "30.0.1", default-features = false, features = ["wgsl-in"] }
