[package]
name = "elysian-preview"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "GPU-agnostic toolpath buffers for preview"

[lints]
workspace = true

[dependencies]
elysian-geom.workspace = true
elysian-slicer.workspace = true
glam.workspace = true
