[package]
name = "elysian-gcode"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
description = "G-code writer and processor"

[lints]
workspace = true

[dependencies]
elysian-config.workspace = true
elysian-geom.workspace = true
elysian-slicer.workspace = true
thiserror.workspace = true

[dev-dependencies]
elysian-model.workspace = true
glam.workspace = true
